// Code generated by go-swagger; DO NOT EDIT.

package hyperflex_software_version_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PatchHyperflexSoftwareVersionPoliciesMoidReader is a Reader for the PatchHyperflexSoftwareVersionPoliciesMoid structure.
type PatchHyperflexSoftwareVersionPoliciesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchHyperflexSoftwareVersionPoliciesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPatchHyperflexSoftwareVersionPoliciesMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPatchHyperflexSoftwareVersionPoliciesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPatchHyperflexSoftwareVersionPoliciesMoidCreated creates a PatchHyperflexSoftwareVersionPoliciesMoidCreated with default headers values
func NewPatchHyperflexSoftwareVersionPoliciesMoidCreated() *PatchHyperflexSoftwareVersionPoliciesMoidCreated {
	return &PatchHyperflexSoftwareVersionPoliciesMoidCreated{}
}

/*PatchHyperflexSoftwareVersionPoliciesMoidCreated handles this case with default header values.

Null response
*/
type PatchHyperflexSoftwareVersionPoliciesMoidCreated struct {
}

func (o *PatchHyperflexSoftwareVersionPoliciesMoidCreated) Error() string {
	return fmt.Sprintf("[PATCH /hyperflex/SoftwareVersionPolicies/{moid}][%d] patchHyperflexSoftwareVersionPoliciesMoidCreated ", 201)
}

func (o *PatchHyperflexSoftwareVersionPoliciesMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchHyperflexSoftwareVersionPoliciesMoidDefault creates a PatchHyperflexSoftwareVersionPoliciesMoidDefault with default headers values
func NewPatchHyperflexSoftwareVersionPoliciesMoidDefault(code int) *PatchHyperflexSoftwareVersionPoliciesMoidDefault {
	return &PatchHyperflexSoftwareVersionPoliciesMoidDefault{
		_statusCode: code,
	}
}

/*PatchHyperflexSoftwareVersionPoliciesMoidDefault handles this case with default header values.

unexpected error
*/
type PatchHyperflexSoftwareVersionPoliciesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the patch hyperflex software version policies moid default response
func (o *PatchHyperflexSoftwareVersionPoliciesMoidDefault) Code() int {
	return o._statusCode
}

func (o *PatchHyperflexSoftwareVersionPoliciesMoidDefault) Error() string {
	return fmt.Sprintf("[PATCH /hyperflex/SoftwareVersionPolicies/{moid}][%d] PatchHyperflexSoftwareVersionPoliciesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PatchHyperflexSoftwareVersionPoliciesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchHyperflexSoftwareVersionPoliciesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
