// Code generated by go-swagger; DO NOT EDIT.

package hcl_service_status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHclServiceStatusesMoidParams creates a new GetHclServiceStatusesMoidParams object
// with the default values initialized.
func NewGetHclServiceStatusesMoidParams() *GetHclServiceStatusesMoidParams {
	var ()
	return &GetHclServiceStatusesMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHclServiceStatusesMoidParamsWithTimeout creates a new GetHclServiceStatusesMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHclServiceStatusesMoidParamsWithTimeout(timeout time.Duration) *GetHclServiceStatusesMoidParams {
	var ()
	return &GetHclServiceStatusesMoidParams{

		timeout: timeout,
	}
}

// NewGetHclServiceStatusesMoidParamsWithContext creates a new GetHclServiceStatusesMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHclServiceStatusesMoidParamsWithContext(ctx context.Context) *GetHclServiceStatusesMoidParams {
	var ()
	return &GetHclServiceStatusesMoidParams{

		Context: ctx,
	}
}

// NewGetHclServiceStatusesMoidParamsWithHTTPClient creates a new GetHclServiceStatusesMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHclServiceStatusesMoidParamsWithHTTPClient(client *http.Client) *GetHclServiceStatusesMoidParams {
	var ()
	return &GetHclServiceStatusesMoidParams{
		HTTPClient: client,
	}
}

/*GetHclServiceStatusesMoidParams contains all the parameters to send to the API endpoint
for the get hcl service statuses moid operation typically these are written to a http.Request
*/
type GetHclServiceStatusesMoidParams struct {

	/*Moid
	  The moid of the hclServiceStatus instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get hcl service statuses moid params
func (o *GetHclServiceStatusesMoidParams) WithTimeout(timeout time.Duration) *GetHclServiceStatusesMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get hcl service statuses moid params
func (o *GetHclServiceStatusesMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get hcl service statuses moid params
func (o *GetHclServiceStatusesMoidParams) WithContext(ctx context.Context) *GetHclServiceStatusesMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get hcl service statuses moid params
func (o *GetHclServiceStatusesMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get hcl service statuses moid params
func (o *GetHclServiceStatusesMoidParams) WithHTTPClient(client *http.Client) *GetHclServiceStatusesMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get hcl service statuses moid params
func (o *GetHclServiceStatusesMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the get hcl service statuses moid params
func (o *GetHclServiceStatusesMoidParams) WithMoid(moid string) *GetHclServiceStatusesMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the get hcl service statuses moid params
func (o *GetHclServiceStatusesMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *GetHclServiceStatusesMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
