// Code generated by go-swagger; DO NOT EDIT.

package hyperflex_server_firmware_version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPostHyperflexServerFirmwareVersionsMoidParams creates a new PostHyperflexServerFirmwareVersionsMoidParams object
// with the default values initialized.
func NewPostHyperflexServerFirmwareVersionsMoidParams() *PostHyperflexServerFirmwareVersionsMoidParams {
	var ()
	return &PostHyperflexServerFirmwareVersionsMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostHyperflexServerFirmwareVersionsMoidParamsWithTimeout creates a new PostHyperflexServerFirmwareVersionsMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostHyperflexServerFirmwareVersionsMoidParamsWithTimeout(timeout time.Duration) *PostHyperflexServerFirmwareVersionsMoidParams {
	var ()
	return &PostHyperflexServerFirmwareVersionsMoidParams{

		timeout: timeout,
	}
}

// NewPostHyperflexServerFirmwareVersionsMoidParamsWithContext creates a new PostHyperflexServerFirmwareVersionsMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostHyperflexServerFirmwareVersionsMoidParamsWithContext(ctx context.Context) *PostHyperflexServerFirmwareVersionsMoidParams {
	var ()
	return &PostHyperflexServerFirmwareVersionsMoidParams{

		Context: ctx,
	}
}

// NewPostHyperflexServerFirmwareVersionsMoidParamsWithHTTPClient creates a new PostHyperflexServerFirmwareVersionsMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostHyperflexServerFirmwareVersionsMoidParamsWithHTTPClient(client *http.Client) *PostHyperflexServerFirmwareVersionsMoidParams {
	var ()
	return &PostHyperflexServerFirmwareVersionsMoidParams{
		HTTPClient: client,
	}
}

/*PostHyperflexServerFirmwareVersionsMoidParams contains all the parameters to send to the API endpoint
for the post hyperflex server firmware versions moid operation typically these are written to a http.Request
*/
type PostHyperflexServerFirmwareVersionsMoidParams struct {

	/*Body
	  hyperflexServerFirmwareVersion to update

	*/
	Body *models.HyperflexServerFirmwareVersion
	/*Moid
	  The moid of the hyperflexServerFirmwareVersion instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post hyperflex server firmware versions moid params
func (o *PostHyperflexServerFirmwareVersionsMoidParams) WithTimeout(timeout time.Duration) *PostHyperflexServerFirmwareVersionsMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post hyperflex server firmware versions moid params
func (o *PostHyperflexServerFirmwareVersionsMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post hyperflex server firmware versions moid params
func (o *PostHyperflexServerFirmwareVersionsMoidParams) WithContext(ctx context.Context) *PostHyperflexServerFirmwareVersionsMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post hyperflex server firmware versions moid params
func (o *PostHyperflexServerFirmwareVersionsMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post hyperflex server firmware versions moid params
func (o *PostHyperflexServerFirmwareVersionsMoidParams) WithHTTPClient(client *http.Client) *PostHyperflexServerFirmwareVersionsMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post hyperflex server firmware versions moid params
func (o *PostHyperflexServerFirmwareVersionsMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post hyperflex server firmware versions moid params
func (o *PostHyperflexServerFirmwareVersionsMoidParams) WithBody(body *models.HyperflexServerFirmwareVersion) *PostHyperflexServerFirmwareVersionsMoidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post hyperflex server firmware versions moid params
func (o *PostHyperflexServerFirmwareVersionsMoidParams) SetBody(body *models.HyperflexServerFirmwareVersion) {
	o.Body = body
}

// WithMoid adds the moid to the post hyperflex server firmware versions moid params
func (o *PostHyperflexServerFirmwareVersionsMoidParams) WithMoid(moid string) *PostHyperflexServerFirmwareVersionsMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the post hyperflex server firmware versions moid params
func (o *PostHyperflexServerFirmwareVersionsMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *PostHyperflexServerFirmwareVersionsMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
