// Code generated by go-swagger; DO NOT EDIT.

package vnic_eth_if

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteVnicEthIfsMoidParams creates a new DeleteVnicEthIfsMoidParams object
// with the default values initialized.
func NewDeleteVnicEthIfsMoidParams() *DeleteVnicEthIfsMoidParams {
	var ()
	return &DeleteVnicEthIfsMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVnicEthIfsMoidParamsWithTimeout creates a new DeleteVnicEthIfsMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteVnicEthIfsMoidParamsWithTimeout(timeout time.Duration) *DeleteVnicEthIfsMoidParams {
	var ()
	return &DeleteVnicEthIfsMoidParams{

		timeout: timeout,
	}
}

// NewDeleteVnicEthIfsMoidParamsWithContext creates a new DeleteVnicEthIfsMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteVnicEthIfsMoidParamsWithContext(ctx context.Context) *DeleteVnicEthIfsMoidParams {
	var ()
	return &DeleteVnicEthIfsMoidParams{

		Context: ctx,
	}
}

// NewDeleteVnicEthIfsMoidParamsWithHTTPClient creates a new DeleteVnicEthIfsMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteVnicEthIfsMoidParamsWithHTTPClient(client *http.Client) *DeleteVnicEthIfsMoidParams {
	var ()
	return &DeleteVnicEthIfsMoidParams{
		HTTPClient: client,
	}
}

/*DeleteVnicEthIfsMoidParams contains all the parameters to send to the API endpoint
for the delete vnic eth ifs moid operation typically these are written to a http.Request
*/
type DeleteVnicEthIfsMoidParams struct {

	/*Moid
	  The moid of the vnicEthIf instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete vnic eth ifs moid params
func (o *DeleteVnicEthIfsMoidParams) WithTimeout(timeout time.Duration) *DeleteVnicEthIfsMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete vnic eth ifs moid params
func (o *DeleteVnicEthIfsMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete vnic eth ifs moid params
func (o *DeleteVnicEthIfsMoidParams) WithContext(ctx context.Context) *DeleteVnicEthIfsMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete vnic eth ifs moid params
func (o *DeleteVnicEthIfsMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete vnic eth ifs moid params
func (o *DeleteVnicEthIfsMoidParams) WithHTTPClient(client *http.Client) *DeleteVnicEthIfsMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete vnic eth ifs moid params
func (o *DeleteVnicEthIfsMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the delete vnic eth ifs moid params
func (o *DeleteVnicEthIfsMoidParams) WithMoid(moid string) *DeleteVnicEthIfsMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the delete vnic eth ifs moid params
func (o *DeleteVnicEthIfsMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVnicEthIfsMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
