// Code generated by go-swagger; DO NOT EDIT.

package iam_ldap_provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPostIamLdapProvidersMoidParams creates a new PostIamLdapProvidersMoidParams object
// with the default values initialized.
func NewPostIamLdapProvidersMoidParams() *PostIamLdapProvidersMoidParams {
	var ()
	return &PostIamLdapProvidersMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostIamLdapProvidersMoidParamsWithTimeout creates a new PostIamLdapProvidersMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostIamLdapProvidersMoidParamsWithTimeout(timeout time.Duration) *PostIamLdapProvidersMoidParams {
	var ()
	return &PostIamLdapProvidersMoidParams{

		timeout: timeout,
	}
}

// NewPostIamLdapProvidersMoidParamsWithContext creates a new PostIamLdapProvidersMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostIamLdapProvidersMoidParamsWithContext(ctx context.Context) *PostIamLdapProvidersMoidParams {
	var ()
	return &PostIamLdapProvidersMoidParams{

		Context: ctx,
	}
}

// NewPostIamLdapProvidersMoidParamsWithHTTPClient creates a new PostIamLdapProvidersMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostIamLdapProvidersMoidParamsWithHTTPClient(client *http.Client) *PostIamLdapProvidersMoidParams {
	var ()
	return &PostIamLdapProvidersMoidParams{
		HTTPClient: client,
	}
}

/*PostIamLdapProvidersMoidParams contains all the parameters to send to the API endpoint
for the post iam ldap providers moid operation typically these are written to a http.Request
*/
type PostIamLdapProvidersMoidParams struct {

	/*Body
	  iamLdapProvider to update

	*/
	Body *models.IamLdapProvider
	/*Moid
	  The moid of the iamLdapProvider instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post iam ldap providers moid params
func (o *PostIamLdapProvidersMoidParams) WithTimeout(timeout time.Duration) *PostIamLdapProvidersMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post iam ldap providers moid params
func (o *PostIamLdapProvidersMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post iam ldap providers moid params
func (o *PostIamLdapProvidersMoidParams) WithContext(ctx context.Context) *PostIamLdapProvidersMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post iam ldap providers moid params
func (o *PostIamLdapProvidersMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post iam ldap providers moid params
func (o *PostIamLdapProvidersMoidParams) WithHTTPClient(client *http.Client) *PostIamLdapProvidersMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post iam ldap providers moid params
func (o *PostIamLdapProvidersMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post iam ldap providers moid params
func (o *PostIamLdapProvidersMoidParams) WithBody(body *models.IamLdapProvider) *PostIamLdapProvidersMoidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post iam ldap providers moid params
func (o *PostIamLdapProvidersMoidParams) SetBody(body *models.IamLdapProvider) {
	o.Body = body
}

// WithMoid adds the moid to the post iam ldap providers moid params
func (o *PostIamLdapProvidersMoidParams) WithMoid(moid string) *PostIamLdapProvidersMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the post iam ldap providers moid params
func (o *PostIamLdapProvidersMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *PostIamLdapProvidersMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
