// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AdapterFcSettings Fibre Channel Settings
//
// Global Fibre Channel settings for this adapter.
//
// swagger:model adapterFcSettings
type AdapterFcSettings struct {

	// Status of FIP protocol on the adapter interfaces.
	//
	FipEnabled bool `json:"FipEnabled,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *AdapterFcSettings) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		FipEnabled bool `json:"FipEnabled,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.FipEnabled = dataAO0.FipEnabled

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m AdapterFcSettings) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		FipEnabled bool `json:"FipEnabled,omitempty"`
	}

	dataAO0.FipEnabled = m.FipEnabled

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this adapter fc settings
func (m *AdapterFcSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *AdapterFcSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdapterFcSettings) UnmarshalBinary(b []byte) error {
	var res AdapterFcSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
