// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ConnectorStreamMessage Connector:Stream Message
//
// The base message to be sent to the stream plugin. Carries information to route the message to the appropriate running stream or create a new stream.
//
// swagger:model connectorStreamMessage
type ConnectorStreamMessage struct {

	// The requested stream name. Stream names are unique per device endpoint.
	//
	StreamName string `json:"StreamName,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ConnectorStreamMessage) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		StreamName string `json:"StreamName,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.StreamName = dataAO0.StreamName

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ConnectorStreamMessage) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		StreamName string `json:"StreamName,omitempty"`
	}

	dataAO0.StreamName = m.StreamName

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this connector stream message
func (m *ConnectorStreamMessage) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ConnectorStreamMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnectorStreamMessage) UnmarshalBinary(b []byte) error {
	var res ConnectorStreamMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
