// Code generated by go-swagger; DO NOT EDIT.

package vnic_fc_adapter_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PostVnicFcAdapterPoliciesReader is a Reader for the PostVnicFcAdapterPolicies structure.
type PostVnicFcAdapterPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostVnicFcAdapterPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostVnicFcAdapterPoliciesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostVnicFcAdapterPoliciesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostVnicFcAdapterPoliciesCreated creates a PostVnicFcAdapterPoliciesCreated with default headers values
func NewPostVnicFcAdapterPoliciesCreated() *PostVnicFcAdapterPoliciesCreated {
	return &PostVnicFcAdapterPoliciesCreated{}
}

/*PostVnicFcAdapterPoliciesCreated handles this case with default header values.

Null response
*/
type PostVnicFcAdapterPoliciesCreated struct {
}

func (o *PostVnicFcAdapterPoliciesCreated) Error() string {
	return fmt.Sprintf("[POST /vnic/FcAdapterPolicies][%d] postVnicFcAdapterPoliciesCreated ", 201)
}

func (o *PostVnicFcAdapterPoliciesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostVnicFcAdapterPoliciesDefault creates a PostVnicFcAdapterPoliciesDefault with default headers values
func NewPostVnicFcAdapterPoliciesDefault(code int) *PostVnicFcAdapterPoliciesDefault {
	return &PostVnicFcAdapterPoliciesDefault{
		_statusCode: code,
	}
}

/*PostVnicFcAdapterPoliciesDefault handles this case with default header values.

unexpected error
*/
type PostVnicFcAdapterPoliciesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post vnic fc adapter policies default response
func (o *PostVnicFcAdapterPoliciesDefault) Code() int {
	return o._statusCode
}

func (o *PostVnicFcAdapterPoliciesDefault) Error() string {
	return fmt.Sprintf("[POST /vnic/FcAdapterPolicies][%d] PostVnicFcAdapterPolicies default  %+v", o._statusCode, o.Payload)
}

func (o *PostVnicFcAdapterPoliciesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostVnicFcAdapterPoliciesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
