// Code generated by go-swagger; DO NOT EDIT.

package iam_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// DeleteIamUsersMoidReader is a Reader for the DeleteIamUsersMoid structure.
type DeleteIamUsersMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteIamUsersMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteIamUsersMoidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteIamUsersMoidNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteIamUsersMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteIamUsersMoidOK creates a DeleteIamUsersMoidOK with default headers values
func NewDeleteIamUsersMoidOK() *DeleteIamUsersMoidOK {
	return &DeleteIamUsersMoidOK{}
}

/*DeleteIamUsersMoidOK handles this case with default header values.

Delete successful.
*/
type DeleteIamUsersMoidOK struct {
}

func (o *DeleteIamUsersMoidOK) Error() string {
	return fmt.Sprintf("[DELETE /iam/Users/{moid}][%d] deleteIamUsersMoidOK ", 200)
}

func (o *DeleteIamUsersMoidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteIamUsersMoidNotFound creates a DeleteIamUsersMoidNotFound with default headers values
func NewDeleteIamUsersMoidNotFound() *DeleteIamUsersMoidNotFound {
	return &DeleteIamUsersMoidNotFound{}
}

/*DeleteIamUsersMoidNotFound handles this case with default header values.

Instance not found.
*/
type DeleteIamUsersMoidNotFound struct {
}

func (o *DeleteIamUsersMoidNotFound) Error() string {
	return fmt.Sprintf("[DELETE /iam/Users/{moid}][%d] deleteIamUsersMoidNotFound ", 404)
}

func (o *DeleteIamUsersMoidNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteIamUsersMoidDefault creates a DeleteIamUsersMoidDefault with default headers values
func NewDeleteIamUsersMoidDefault(code int) *DeleteIamUsersMoidDefault {
	return &DeleteIamUsersMoidDefault{
		_statusCode: code,
	}
}

/*DeleteIamUsersMoidDefault handles this case with default header values.

Unexpected error
*/
type DeleteIamUsersMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete iam users moid default response
func (o *DeleteIamUsersMoidDefault) Code() int {
	return o._statusCode
}

func (o *DeleteIamUsersMoidDefault) Error() string {
	return fmt.Sprintf("[DELETE /iam/Users/{moid}][%d] DeleteIamUsersMoid default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteIamUsersMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteIamUsersMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
