// Code generated by go-swagger; DO NOT EDIT.

package softwarerepository_authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PostSoftwarerepositoryAuthorizationsMoidReader is a Reader for the PostSoftwarerepositoryAuthorizationsMoid structure.
type PostSoftwarerepositoryAuthorizationsMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSoftwarerepositoryAuthorizationsMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostSoftwarerepositoryAuthorizationsMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostSoftwarerepositoryAuthorizationsMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostSoftwarerepositoryAuthorizationsMoidCreated creates a PostSoftwarerepositoryAuthorizationsMoidCreated with default headers values
func NewPostSoftwarerepositoryAuthorizationsMoidCreated() *PostSoftwarerepositoryAuthorizationsMoidCreated {
	return &PostSoftwarerepositoryAuthorizationsMoidCreated{}
}

/*PostSoftwarerepositoryAuthorizationsMoidCreated handles this case with default header values.

Null response
*/
type PostSoftwarerepositoryAuthorizationsMoidCreated struct {
}

func (o *PostSoftwarerepositoryAuthorizationsMoidCreated) Error() string {
	return fmt.Sprintf("[POST /softwarerepository/Authorizations/{moid}][%d] postSoftwarerepositoryAuthorizationsMoidCreated ", 201)
}

func (o *PostSoftwarerepositoryAuthorizationsMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostSoftwarerepositoryAuthorizationsMoidDefault creates a PostSoftwarerepositoryAuthorizationsMoidDefault with default headers values
func NewPostSoftwarerepositoryAuthorizationsMoidDefault(code int) *PostSoftwarerepositoryAuthorizationsMoidDefault {
	return &PostSoftwarerepositoryAuthorizationsMoidDefault{
		_statusCode: code,
	}
}

/*PostSoftwarerepositoryAuthorizationsMoidDefault handles this case with default header values.

unexpected error
*/
type PostSoftwarerepositoryAuthorizationsMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post softwarerepository authorizations moid default response
func (o *PostSoftwarerepositoryAuthorizationsMoidDefault) Code() int {
	return o._statusCode
}

func (o *PostSoftwarerepositoryAuthorizationsMoidDefault) Error() string {
	return fmt.Sprintf("[POST /softwarerepository/Authorizations/{moid}][%d] PostSoftwarerepositoryAuthorizationsMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PostSoftwarerepositoryAuthorizationsMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostSoftwarerepositoryAuthorizationsMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
