// Code generated by go-swagger; DO NOT EDIT.

package hyperflex_server_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteHyperflexServerModelsMoidParams creates a new DeleteHyperflexServerModelsMoidParams object
// with the default values initialized.
func NewDeleteHyperflexServerModelsMoidParams() *DeleteHyperflexServerModelsMoidParams {
	var ()
	return &DeleteHyperflexServerModelsMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteHyperflexServerModelsMoidParamsWithTimeout creates a new DeleteHyperflexServerModelsMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteHyperflexServerModelsMoidParamsWithTimeout(timeout time.Duration) *DeleteHyperflexServerModelsMoidParams {
	var ()
	return &DeleteHyperflexServerModelsMoidParams{

		timeout: timeout,
	}
}

// NewDeleteHyperflexServerModelsMoidParamsWithContext creates a new DeleteHyperflexServerModelsMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteHyperflexServerModelsMoidParamsWithContext(ctx context.Context) *DeleteHyperflexServerModelsMoidParams {
	var ()
	return &DeleteHyperflexServerModelsMoidParams{

		Context: ctx,
	}
}

// NewDeleteHyperflexServerModelsMoidParamsWithHTTPClient creates a new DeleteHyperflexServerModelsMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteHyperflexServerModelsMoidParamsWithHTTPClient(client *http.Client) *DeleteHyperflexServerModelsMoidParams {
	var ()
	return &DeleteHyperflexServerModelsMoidParams{
		HTTPClient: client,
	}
}

/*DeleteHyperflexServerModelsMoidParams contains all the parameters to send to the API endpoint
for the delete hyperflex server models moid operation typically these are written to a http.Request
*/
type DeleteHyperflexServerModelsMoidParams struct {

	/*Moid
	  The moid of the hyperflexServerModel instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete hyperflex server models moid params
func (o *DeleteHyperflexServerModelsMoidParams) WithTimeout(timeout time.Duration) *DeleteHyperflexServerModelsMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete hyperflex server models moid params
func (o *DeleteHyperflexServerModelsMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete hyperflex server models moid params
func (o *DeleteHyperflexServerModelsMoidParams) WithContext(ctx context.Context) *DeleteHyperflexServerModelsMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete hyperflex server models moid params
func (o *DeleteHyperflexServerModelsMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete hyperflex server models moid params
func (o *DeleteHyperflexServerModelsMoidParams) WithHTTPClient(client *http.Client) *DeleteHyperflexServerModelsMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete hyperflex server models moid params
func (o *DeleteHyperflexServerModelsMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the delete hyperflex server models moid params
func (o *DeleteHyperflexServerModelsMoidParams) WithMoid(moid string) *DeleteHyperflexServerModelsMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the delete hyperflex server models moid params
func (o *DeleteHyperflexServerModelsMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteHyperflexServerModelsMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
