// Code generated by go-swagger; DO NOT EDIT.

package hyperflex_cluster_network_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PatchHyperflexClusterNetworkPoliciesMoidReader is a Reader for the PatchHyperflexClusterNetworkPoliciesMoid structure.
type PatchHyperflexClusterNetworkPoliciesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchHyperflexClusterNetworkPoliciesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPatchHyperflexClusterNetworkPoliciesMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPatchHyperflexClusterNetworkPoliciesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPatchHyperflexClusterNetworkPoliciesMoidCreated creates a PatchHyperflexClusterNetworkPoliciesMoidCreated with default headers values
func NewPatchHyperflexClusterNetworkPoliciesMoidCreated() *PatchHyperflexClusterNetworkPoliciesMoidCreated {
	return &PatchHyperflexClusterNetworkPoliciesMoidCreated{}
}

/*PatchHyperflexClusterNetworkPoliciesMoidCreated handles this case with default header values.

Null response
*/
type PatchHyperflexClusterNetworkPoliciesMoidCreated struct {
}

func (o *PatchHyperflexClusterNetworkPoliciesMoidCreated) Error() string {
	return fmt.Sprintf("[PATCH /hyperflex/ClusterNetworkPolicies/{moid}][%d] patchHyperflexClusterNetworkPoliciesMoidCreated ", 201)
}

func (o *PatchHyperflexClusterNetworkPoliciesMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchHyperflexClusterNetworkPoliciesMoidDefault creates a PatchHyperflexClusterNetworkPoliciesMoidDefault with default headers values
func NewPatchHyperflexClusterNetworkPoliciesMoidDefault(code int) *PatchHyperflexClusterNetworkPoliciesMoidDefault {
	return &PatchHyperflexClusterNetworkPoliciesMoidDefault{
		_statusCode: code,
	}
}

/*PatchHyperflexClusterNetworkPoliciesMoidDefault handles this case with default header values.

unexpected error
*/
type PatchHyperflexClusterNetworkPoliciesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the patch hyperflex cluster network policies moid default response
func (o *PatchHyperflexClusterNetworkPoliciesMoidDefault) Code() int {
	return o._statusCode
}

func (o *PatchHyperflexClusterNetworkPoliciesMoidDefault) Error() string {
	return fmt.Sprintf("[PATCH /hyperflex/ClusterNetworkPolicies/{moid}][%d] PatchHyperflexClusterNetworkPoliciesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PatchHyperflexClusterNetworkPoliciesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchHyperflexClusterNetworkPoliciesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
