// Code generated by go-swagger; DO NOT EDIT.

package ssh_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// DeleteSSHPoliciesMoidReader is a Reader for the DeleteSSHPoliciesMoid structure.
type DeleteSSHPoliciesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSSHPoliciesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSSHPoliciesMoidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteSSHPoliciesMoidNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteSSHPoliciesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteSSHPoliciesMoidOK creates a DeleteSSHPoliciesMoidOK with default headers values
func NewDeleteSSHPoliciesMoidOK() *DeleteSSHPoliciesMoidOK {
	return &DeleteSSHPoliciesMoidOK{}
}

/*DeleteSSHPoliciesMoidOK handles this case with default header values.

Delete successful.
*/
type DeleteSSHPoliciesMoidOK struct {
}

func (o *DeleteSSHPoliciesMoidOK) Error() string {
	return fmt.Sprintf("[DELETE /ssh/Policies/{moid}][%d] deleteSshPoliciesMoidOK ", 200)
}

func (o *DeleteSSHPoliciesMoidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSSHPoliciesMoidNotFound creates a DeleteSSHPoliciesMoidNotFound with default headers values
func NewDeleteSSHPoliciesMoidNotFound() *DeleteSSHPoliciesMoidNotFound {
	return &DeleteSSHPoliciesMoidNotFound{}
}

/*DeleteSSHPoliciesMoidNotFound handles this case with default header values.

Instance not found.
*/
type DeleteSSHPoliciesMoidNotFound struct {
}

func (o *DeleteSSHPoliciesMoidNotFound) Error() string {
	return fmt.Sprintf("[DELETE /ssh/Policies/{moid}][%d] deleteSshPoliciesMoidNotFound ", 404)
}

func (o *DeleteSSHPoliciesMoidNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSSHPoliciesMoidDefault creates a DeleteSSHPoliciesMoidDefault with default headers values
func NewDeleteSSHPoliciesMoidDefault(code int) *DeleteSSHPoliciesMoidDefault {
	return &DeleteSSHPoliciesMoidDefault{
		_statusCode: code,
	}
}

/*DeleteSSHPoliciesMoidDefault handles this case with default header values.

Unexpected error
*/
type DeleteSSHPoliciesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete SSH policies moid default response
func (o *DeleteSSHPoliciesMoidDefault) Code() int {
	return o._statusCode
}

func (o *DeleteSSHPoliciesMoidDefault) Error() string {
	return fmt.Sprintf("[DELETE /ssh/Policies/{moid}][%d] DeleteSSHPoliciesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSSHPoliciesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteSSHPoliciesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
