// Code generated by go-swagger; DO NOT EDIT.

package niaapi_apic_sweol

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNiaapiApicSweolsMoidParams creates a new GetNiaapiApicSweolsMoidParams object
// with the default values initialized.
func NewGetNiaapiApicSweolsMoidParams() *GetNiaapiApicSweolsMoidParams {
	var ()
	return &GetNiaapiApicSweolsMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNiaapiApicSweolsMoidParamsWithTimeout creates a new GetNiaapiApicSweolsMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNiaapiApicSweolsMoidParamsWithTimeout(timeout time.Duration) *GetNiaapiApicSweolsMoidParams {
	var ()
	return &GetNiaapiApicSweolsMoidParams{

		timeout: timeout,
	}
}

// NewGetNiaapiApicSweolsMoidParamsWithContext creates a new GetNiaapiApicSweolsMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNiaapiApicSweolsMoidParamsWithContext(ctx context.Context) *GetNiaapiApicSweolsMoidParams {
	var ()
	return &GetNiaapiApicSweolsMoidParams{

		Context: ctx,
	}
}

// NewGetNiaapiApicSweolsMoidParamsWithHTTPClient creates a new GetNiaapiApicSweolsMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNiaapiApicSweolsMoidParamsWithHTTPClient(client *http.Client) *GetNiaapiApicSweolsMoidParams {
	var ()
	return &GetNiaapiApicSweolsMoidParams{
		HTTPClient: client,
	}
}

/*GetNiaapiApicSweolsMoidParams contains all the parameters to send to the API endpoint
for the get niaapi apic sweols moid operation typically these are written to a http.Request
*/
type GetNiaapiApicSweolsMoidParams struct {

	/*Moid
	  The moid of the niaapiApicSweol instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get niaapi apic sweols moid params
func (o *GetNiaapiApicSweolsMoidParams) WithTimeout(timeout time.Duration) *GetNiaapiApicSweolsMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get niaapi apic sweols moid params
func (o *GetNiaapiApicSweolsMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get niaapi apic sweols moid params
func (o *GetNiaapiApicSweolsMoidParams) WithContext(ctx context.Context) *GetNiaapiApicSweolsMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get niaapi apic sweols moid params
func (o *GetNiaapiApicSweolsMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get niaapi apic sweols moid params
func (o *GetNiaapiApicSweolsMoidParams) WithHTTPClient(client *http.Client) *GetNiaapiApicSweolsMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get niaapi apic sweols moid params
func (o *GetNiaapiApicSweolsMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the get niaapi apic sweols moid params
func (o *GetNiaapiApicSweolsMoidParams) WithMoid(moid string) *GetNiaapiApicSweolsMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the get niaapi apic sweols moid params
func (o *GetNiaapiApicSweolsMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *GetNiaapiApicSweolsMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
