// Code generated by go-swagger; DO NOT EDIT.

package bios_unit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// GetBiosUnitsMoidReader is a Reader for the GetBiosUnitsMoid structure.
type GetBiosUnitsMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBiosUnitsMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBiosUnitsMoidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetBiosUnitsMoidNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetBiosUnitsMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetBiosUnitsMoidOK creates a GetBiosUnitsMoidOK with default headers values
func NewGetBiosUnitsMoidOK() *GetBiosUnitsMoidOK {
	return &GetBiosUnitsMoidOK{}
}

/*GetBiosUnitsMoidOK handles this case with default header values.

An instance of biosUnit
*/
type GetBiosUnitsMoidOK struct {
	Payload *models.BiosUnit
}

func (o *GetBiosUnitsMoidOK) Error() string {
	return fmt.Sprintf("[GET /bios/Units/{moid}][%d] getBiosUnitsMoidOK  %+v", 200, o.Payload)
}

func (o *GetBiosUnitsMoidOK) GetPayload() *models.BiosUnit {
	return o.Payload
}

func (o *GetBiosUnitsMoidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BiosUnit)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBiosUnitsMoidNotFound creates a GetBiosUnitsMoidNotFound with default headers values
func NewGetBiosUnitsMoidNotFound() *GetBiosUnitsMoidNotFound {
	return &GetBiosUnitsMoidNotFound{}
}

/*GetBiosUnitsMoidNotFound handles this case with default header values.

Instance not found.
*/
type GetBiosUnitsMoidNotFound struct {
}

func (o *GetBiosUnitsMoidNotFound) Error() string {
	return fmt.Sprintf("[GET /bios/Units/{moid}][%d] getBiosUnitsMoidNotFound ", 404)
}

func (o *GetBiosUnitsMoidNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetBiosUnitsMoidDefault creates a GetBiosUnitsMoidDefault with default headers values
func NewGetBiosUnitsMoidDefault(code int) *GetBiosUnitsMoidDefault {
	return &GetBiosUnitsMoidDefault{
		_statusCode: code,
	}
}

/*GetBiosUnitsMoidDefault handles this case with default header values.

Unexpected error
*/
type GetBiosUnitsMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get bios units moid default response
func (o *GetBiosUnitsMoidDefault) Code() int {
	return o._statusCode
}

func (o *GetBiosUnitsMoidDefault) Error() string {
	return fmt.Sprintf("[GET /bios/Units/{moid}][%d] GetBiosUnitsMoid default  %+v", o._statusCode, o.Payload)
}

func (o *GetBiosUnitsMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBiosUnitsMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
