// Code generated by go-swagger; DO NOT EDIT.

package equipment_chassis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPatchEquipmentChassesMoidParams creates a new PatchEquipmentChassesMoidParams object
// with the default values initialized.
func NewPatchEquipmentChassesMoidParams() *PatchEquipmentChassesMoidParams {
	var ()
	return &PatchEquipmentChassesMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchEquipmentChassesMoidParamsWithTimeout creates a new PatchEquipmentChassesMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchEquipmentChassesMoidParamsWithTimeout(timeout time.Duration) *PatchEquipmentChassesMoidParams {
	var ()
	return &PatchEquipmentChassesMoidParams{

		timeout: timeout,
	}
}

// NewPatchEquipmentChassesMoidParamsWithContext creates a new PatchEquipmentChassesMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchEquipmentChassesMoidParamsWithContext(ctx context.Context) *PatchEquipmentChassesMoidParams {
	var ()
	return &PatchEquipmentChassesMoidParams{

		Context: ctx,
	}
}

// NewPatchEquipmentChassesMoidParamsWithHTTPClient creates a new PatchEquipmentChassesMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchEquipmentChassesMoidParamsWithHTTPClient(client *http.Client) *PatchEquipmentChassesMoidParams {
	var ()
	return &PatchEquipmentChassesMoidParams{
		HTTPClient: client,
	}
}

/*PatchEquipmentChassesMoidParams contains all the parameters to send to the API endpoint
for the patch equipment chasses moid operation typically these are written to a http.Request
*/
type PatchEquipmentChassesMoidParams struct {

	/*Body
	  equipmentChassis to update

	*/
	Body *models.EquipmentChassis
	/*Moid
	  The moid of the equipmentChassis instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch equipment chasses moid params
func (o *PatchEquipmentChassesMoidParams) WithTimeout(timeout time.Duration) *PatchEquipmentChassesMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch equipment chasses moid params
func (o *PatchEquipmentChassesMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch equipment chasses moid params
func (o *PatchEquipmentChassesMoidParams) WithContext(ctx context.Context) *PatchEquipmentChassesMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch equipment chasses moid params
func (o *PatchEquipmentChassesMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch equipment chasses moid params
func (o *PatchEquipmentChassesMoidParams) WithHTTPClient(client *http.Client) *PatchEquipmentChassesMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch equipment chasses moid params
func (o *PatchEquipmentChassesMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch equipment chasses moid params
func (o *PatchEquipmentChassesMoidParams) WithBody(body *models.EquipmentChassis) *PatchEquipmentChassesMoidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch equipment chasses moid params
func (o *PatchEquipmentChassesMoidParams) SetBody(body *models.EquipmentChassis) {
	o.Body = body
}

// WithMoid adds the moid to the patch equipment chasses moid params
func (o *PatchEquipmentChassesMoidParams) WithMoid(moid string) *PatchEquipmentChassesMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the patch equipment chasses moid params
func (o *PatchEquipmentChassesMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *PatchEquipmentChassesMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
