// Code generated by go-swagger; DO NOT EDIT.

package resource_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PostResourceGroupsMoidReader is a Reader for the PostResourceGroupsMoid structure.
type PostResourceGroupsMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostResourceGroupsMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostResourceGroupsMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostResourceGroupsMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostResourceGroupsMoidCreated creates a PostResourceGroupsMoidCreated with default headers values
func NewPostResourceGroupsMoidCreated() *PostResourceGroupsMoidCreated {
	return &PostResourceGroupsMoidCreated{}
}

/*PostResourceGroupsMoidCreated handles this case with default header values.

Null response
*/
type PostResourceGroupsMoidCreated struct {
}

func (o *PostResourceGroupsMoidCreated) Error() string {
	return fmt.Sprintf("[POST /resource/Groups/{moid}][%d] postResourceGroupsMoidCreated ", 201)
}

func (o *PostResourceGroupsMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostResourceGroupsMoidDefault creates a PostResourceGroupsMoidDefault with default headers values
func NewPostResourceGroupsMoidDefault(code int) *PostResourceGroupsMoidDefault {
	return &PostResourceGroupsMoidDefault{
		_statusCode: code,
	}
}

/*PostResourceGroupsMoidDefault handles this case with default header values.

unexpected error
*/
type PostResourceGroupsMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post resource groups moid default response
func (o *PostResourceGroupsMoidDefault) Code() int {
	return o._statusCode
}

func (o *PostResourceGroupsMoidDefault) Error() string {
	return fmt.Sprintf("[POST /resource/Groups/{moid}][%d] PostResourceGroupsMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PostResourceGroupsMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostResourceGroupsMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
