// Code generated by go-swagger; DO NOT EDIT.

package appliance_backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// DeleteApplianceBackupsMoidReader is a Reader for the DeleteApplianceBackupsMoid structure.
type DeleteApplianceBackupsMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteApplianceBackupsMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApplianceBackupsMoidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteApplianceBackupsMoidNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteApplianceBackupsMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteApplianceBackupsMoidOK creates a DeleteApplianceBackupsMoidOK with default headers values
func NewDeleteApplianceBackupsMoidOK() *DeleteApplianceBackupsMoidOK {
	return &DeleteApplianceBackupsMoidOK{}
}

/*DeleteApplianceBackupsMoidOK handles this case with default header values.

Delete successful.
*/
type DeleteApplianceBackupsMoidOK struct {
}

func (o *DeleteApplianceBackupsMoidOK) Error() string {
	return fmt.Sprintf("[DELETE /appliance/Backups/{moid}][%d] deleteApplianceBackupsMoidOK ", 200)
}

func (o *DeleteApplianceBackupsMoidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteApplianceBackupsMoidNotFound creates a DeleteApplianceBackupsMoidNotFound with default headers values
func NewDeleteApplianceBackupsMoidNotFound() *DeleteApplianceBackupsMoidNotFound {
	return &DeleteApplianceBackupsMoidNotFound{}
}

/*DeleteApplianceBackupsMoidNotFound handles this case with default header values.

Instance not found.
*/
type DeleteApplianceBackupsMoidNotFound struct {
}

func (o *DeleteApplianceBackupsMoidNotFound) Error() string {
	return fmt.Sprintf("[DELETE /appliance/Backups/{moid}][%d] deleteApplianceBackupsMoidNotFound ", 404)
}

func (o *DeleteApplianceBackupsMoidNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteApplianceBackupsMoidDefault creates a DeleteApplianceBackupsMoidDefault with default headers values
func NewDeleteApplianceBackupsMoidDefault(code int) *DeleteApplianceBackupsMoidDefault {
	return &DeleteApplianceBackupsMoidDefault{
		_statusCode: code,
	}
}

/*DeleteApplianceBackupsMoidDefault handles this case with default header values.

Unexpected error
*/
type DeleteApplianceBackupsMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete appliance backups moid default response
func (o *DeleteApplianceBackupsMoidDefault) Code() int {
	return o._statusCode
}

func (o *DeleteApplianceBackupsMoidDefault) Error() string {
	return fmt.Sprintf("[DELETE /appliance/Backups/{moid}][%d] DeleteApplianceBackupsMoid default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteApplianceBackupsMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteApplianceBackupsMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
