// Code generated by go-swagger; DO NOT EDIT.

package telemetry_time_series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new telemetry time series API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for telemetry time series API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetTelemetryTimeSeries gets a list of telemetry time series instances
*/
func (a *Client) GetTelemetryTimeSeries(params *GetTelemetryTimeSeriesParams) (*GetTelemetryTimeSeriesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTelemetryTimeSeriesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetTelemetryTimeSeries",
		Method:             "GET",
		PathPattern:        "/telemetry/TimeSeries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetTelemetryTimeSeriesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetTelemetryTimeSeriesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetTelemetryTimeSeriesDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetTelemetryTimeSeriesMoid gets a specific instance of telemetry time series
*/
func (a *Client) GetTelemetryTimeSeriesMoid(params *GetTelemetryTimeSeriesMoidParams) (*GetTelemetryTimeSeriesMoidOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTelemetryTimeSeriesMoidParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetTelemetryTimeSeriesMoid",
		Method:             "GET",
		PathPattern:        "/telemetry/TimeSeries/{moid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetTelemetryTimeSeriesMoidReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetTelemetryTimeSeriesMoidOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetTelemetryTimeSeriesMoidDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostTelemetryTimeSeries creates an instance of telemetry time series
*/
func (a *Client) PostTelemetryTimeSeries(params *PostTelemetryTimeSeriesParams) (*PostTelemetryTimeSeriesCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostTelemetryTimeSeriesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostTelemetryTimeSeries",
		Method:             "POST",
		PathPattern:        "/telemetry/TimeSeries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostTelemetryTimeSeriesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostTelemetryTimeSeriesCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PostTelemetryTimeSeriesDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
