// Code generated by go-swagger; DO NOT EDIT.

package iam_domain_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// GetIamDomainGroupsReader is a Reader for the GetIamDomainGroups structure.
type GetIamDomainGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIamDomainGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIamDomainGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetIamDomainGroupsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetIamDomainGroupsOK creates a GetIamDomainGroupsOK with default headers values
func NewGetIamDomainGroupsOK() *GetIamDomainGroupsOK {
	return &GetIamDomainGroupsOK{}
}

/*GetIamDomainGroupsOK handles this case with default header values.

List of iamDomainGroups for the given filter criteria
*/
type GetIamDomainGroupsOK struct {
	Payload *models.IamDomainGroupList
}

func (o *GetIamDomainGroupsOK) Error() string {
	return fmt.Sprintf("[GET /iam/DomainGroups][%d] getIamDomainGroupsOK  %+v", 200, o.Payload)
}

func (o *GetIamDomainGroupsOK) GetPayload() *models.IamDomainGroupList {
	return o.Payload
}

func (o *GetIamDomainGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IamDomainGroupList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIamDomainGroupsDefault creates a GetIamDomainGroupsDefault with default headers values
func NewGetIamDomainGroupsDefault(code int) *GetIamDomainGroupsDefault {
	return &GetIamDomainGroupsDefault{
		_statusCode: code,
	}
}

/*GetIamDomainGroupsDefault handles this case with default header values.

Unexpected error
*/
type GetIamDomainGroupsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get iam domain groups default response
func (o *GetIamDomainGroupsDefault) Code() int {
	return o._statusCode
}

func (o *GetIamDomainGroupsDefault) Error() string {
	return fmt.Sprintf("[GET /iam/DomainGroups][%d] GetIamDomainGroups default  %+v", o._statusCode, o.Payload)
}

func (o *GetIamDomainGroupsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetIamDomainGroupsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
