// Code generated by go-swagger; DO NOT EDIT.

package equipment_rack_enclosure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEquipmentRackEnclosuresMoidParams creates a new GetEquipmentRackEnclosuresMoidParams object
// with the default values initialized.
func NewGetEquipmentRackEnclosuresMoidParams() *GetEquipmentRackEnclosuresMoidParams {
	var ()
	return &GetEquipmentRackEnclosuresMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEquipmentRackEnclosuresMoidParamsWithTimeout creates a new GetEquipmentRackEnclosuresMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEquipmentRackEnclosuresMoidParamsWithTimeout(timeout time.Duration) *GetEquipmentRackEnclosuresMoidParams {
	var ()
	return &GetEquipmentRackEnclosuresMoidParams{

		timeout: timeout,
	}
}

// NewGetEquipmentRackEnclosuresMoidParamsWithContext creates a new GetEquipmentRackEnclosuresMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEquipmentRackEnclosuresMoidParamsWithContext(ctx context.Context) *GetEquipmentRackEnclosuresMoidParams {
	var ()
	return &GetEquipmentRackEnclosuresMoidParams{

		Context: ctx,
	}
}

// NewGetEquipmentRackEnclosuresMoidParamsWithHTTPClient creates a new GetEquipmentRackEnclosuresMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEquipmentRackEnclosuresMoidParamsWithHTTPClient(client *http.Client) *GetEquipmentRackEnclosuresMoidParams {
	var ()
	return &GetEquipmentRackEnclosuresMoidParams{
		HTTPClient: client,
	}
}

/*GetEquipmentRackEnclosuresMoidParams contains all the parameters to send to the API endpoint
for the get equipment rack enclosures moid operation typically these are written to a http.Request
*/
type GetEquipmentRackEnclosuresMoidParams struct {

	/*Moid
	  The moid of the equipmentRackEnclosure instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get equipment rack enclosures moid params
func (o *GetEquipmentRackEnclosuresMoidParams) WithTimeout(timeout time.Duration) *GetEquipmentRackEnclosuresMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get equipment rack enclosures moid params
func (o *GetEquipmentRackEnclosuresMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get equipment rack enclosures moid params
func (o *GetEquipmentRackEnclosuresMoidParams) WithContext(ctx context.Context) *GetEquipmentRackEnclosuresMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get equipment rack enclosures moid params
func (o *GetEquipmentRackEnclosuresMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get equipment rack enclosures moid params
func (o *GetEquipmentRackEnclosuresMoidParams) WithHTTPClient(client *http.Client) *GetEquipmentRackEnclosuresMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get equipment rack enclosures moid params
func (o *GetEquipmentRackEnclosuresMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the get equipment rack enclosures moid params
func (o *GetEquipmentRackEnclosuresMoidParams) WithMoid(moid string) *GetEquipmentRackEnclosuresMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the get equipment rack enclosures moid params
func (o *GetEquipmentRackEnclosuresMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *GetEquipmentRackEnclosuresMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
