// Code generated by go-swagger; DO NOT EDIT.

package cond_alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCondAlarmsMoidParams creates a new GetCondAlarmsMoidParams object
// with the default values initialized.
func NewGetCondAlarmsMoidParams() *GetCondAlarmsMoidParams {
	var ()
	return &GetCondAlarmsMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCondAlarmsMoidParamsWithTimeout creates a new GetCondAlarmsMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCondAlarmsMoidParamsWithTimeout(timeout time.Duration) *GetCondAlarmsMoidParams {
	var ()
	return &GetCondAlarmsMoidParams{

		timeout: timeout,
	}
}

// NewGetCondAlarmsMoidParamsWithContext creates a new GetCondAlarmsMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCondAlarmsMoidParamsWithContext(ctx context.Context) *GetCondAlarmsMoidParams {
	var ()
	return &GetCondAlarmsMoidParams{

		Context: ctx,
	}
}

// NewGetCondAlarmsMoidParamsWithHTTPClient creates a new GetCondAlarmsMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCondAlarmsMoidParamsWithHTTPClient(client *http.Client) *GetCondAlarmsMoidParams {
	var ()
	return &GetCondAlarmsMoidParams{
		HTTPClient: client,
	}
}

/*GetCondAlarmsMoidParams contains all the parameters to send to the API endpoint
for the get cond alarms moid operation typically these are written to a http.Request
*/
type GetCondAlarmsMoidParams struct {

	/*Moid
	  The moid of the condAlarm instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cond alarms moid params
func (o *GetCondAlarmsMoidParams) WithTimeout(timeout time.Duration) *GetCondAlarmsMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cond alarms moid params
func (o *GetCondAlarmsMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cond alarms moid params
func (o *GetCondAlarmsMoidParams) WithContext(ctx context.Context) *GetCondAlarmsMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cond alarms moid params
func (o *GetCondAlarmsMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cond alarms moid params
func (o *GetCondAlarmsMoidParams) WithHTTPClient(client *http.Client) *GetCondAlarmsMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cond alarms moid params
func (o *GetCondAlarmsMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the get cond alarms moid params
func (o *GetCondAlarmsMoidParams) WithMoid(moid string) *GetCondAlarmsMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the get cond alarms moid params
func (o *GetCondAlarmsMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *GetCondAlarmsMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
