// Code generated by go-swagger; DO NOT EDIT.

package cond_alarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// GetCondAlarmsReader is a Reader for the GetCondAlarms structure.
type GetCondAlarmsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCondAlarmsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCondAlarmsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetCondAlarmsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCondAlarmsOK creates a GetCondAlarmsOK with default headers values
func NewGetCondAlarmsOK() *GetCondAlarmsOK {
	return &GetCondAlarmsOK{}
}

/*GetCondAlarmsOK handles this case with default header values.

List of condAlarms for the given filter criteria
*/
type GetCondAlarmsOK struct {
	Payload *models.CondAlarmList
}

func (o *GetCondAlarmsOK) Error() string {
	return fmt.Sprintf("[GET /cond/Alarms][%d] getCondAlarmsOK  %+v", 200, o.Payload)
}

func (o *GetCondAlarmsOK) GetPayload() *models.CondAlarmList {
	return o.Payload
}

func (o *GetCondAlarmsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CondAlarmList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCondAlarmsDefault creates a GetCondAlarmsDefault with default headers values
func NewGetCondAlarmsDefault(code int) *GetCondAlarmsDefault {
	return &GetCondAlarmsDefault{
		_statusCode: code,
	}
}

/*GetCondAlarmsDefault handles this case with default header values.

Unexpected error
*/
type GetCondAlarmsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get cond alarms default response
func (o *GetCondAlarmsDefault) Code() int {
	return o._statusCode
}

func (o *GetCondAlarmsDefault) Error() string {
	return fmt.Sprintf("[GET /cond/Alarms][%d] GetCondAlarms default  %+v", o._statusCode, o.Payload)
}

func (o *GetCondAlarmsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetCondAlarmsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
