// Code generated by go-swagger; DO NOT EDIT.

package hcl_exempted_catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// GetHclExemptedCatalogsReader is a Reader for the GetHclExemptedCatalogs structure.
type GetHclExemptedCatalogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHclExemptedCatalogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHclExemptedCatalogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetHclExemptedCatalogsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetHclExemptedCatalogsOK creates a GetHclExemptedCatalogsOK with default headers values
func NewGetHclExemptedCatalogsOK() *GetHclExemptedCatalogsOK {
	return &GetHclExemptedCatalogsOK{}
}

/*GetHclExemptedCatalogsOK handles this case with default header values.

List of hclExemptedCatalogs for the given filter criteria
*/
type GetHclExemptedCatalogsOK struct {
	Payload *models.HclExemptedCatalogList
}

func (o *GetHclExemptedCatalogsOK) Error() string {
	return fmt.Sprintf("[GET /hcl/ExemptedCatalogs][%d] getHclExemptedCatalogsOK  %+v", 200, o.Payload)
}

func (o *GetHclExemptedCatalogsOK) GetPayload() *models.HclExemptedCatalogList {
	return o.Payload
}

func (o *GetHclExemptedCatalogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HclExemptedCatalogList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHclExemptedCatalogsDefault creates a GetHclExemptedCatalogsDefault with default headers values
func NewGetHclExemptedCatalogsDefault(code int) *GetHclExemptedCatalogsDefault {
	return &GetHclExemptedCatalogsDefault{
		_statusCode: code,
	}
}

/*GetHclExemptedCatalogsDefault handles this case with default header values.

Unexpected error
*/
type GetHclExemptedCatalogsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get hcl exempted catalogs default response
func (o *GetHclExemptedCatalogsDefault) Code() int {
	return o._statusCode
}

func (o *GetHclExemptedCatalogsDefault) Error() string {
	return fmt.Sprintf("[GET /hcl/ExemptedCatalogs][%d] GetHclExemptedCatalogs default  %+v", o._statusCode, o.Payload)
}

func (o *GetHclExemptedCatalogsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetHclExemptedCatalogsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
