// Code generated by go-swagger; DO NOT EDIT.

package appliance_upgrade

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// GetApplianceUpgradesReader is a Reader for the GetApplianceUpgrades structure.
type GetApplianceUpgradesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplianceUpgradesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApplianceUpgradesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetApplianceUpgradesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetApplianceUpgradesOK creates a GetApplianceUpgradesOK with default headers values
func NewGetApplianceUpgradesOK() *GetApplianceUpgradesOK {
	return &GetApplianceUpgradesOK{}
}

/*GetApplianceUpgradesOK handles this case with default header values.

List of applianceUpgrades for the given filter criteria
*/
type GetApplianceUpgradesOK struct {
	Payload *models.ApplianceUpgradeList
}

func (o *GetApplianceUpgradesOK) Error() string {
	return fmt.Sprintf("[GET /appliance/Upgrades][%d] getApplianceUpgradesOK  %+v", 200, o.Payload)
}

func (o *GetApplianceUpgradesOK) GetPayload() *models.ApplianceUpgradeList {
	return o.Payload
}

func (o *GetApplianceUpgradesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplianceUpgradeList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplianceUpgradesDefault creates a GetApplianceUpgradesDefault with default headers values
func NewGetApplianceUpgradesDefault(code int) *GetApplianceUpgradesDefault {
	return &GetApplianceUpgradesDefault{
		_statusCode: code,
	}
}

/*GetApplianceUpgradesDefault handles this case with default header values.

Unexpected error
*/
type GetApplianceUpgradesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get appliance upgrades default response
func (o *GetApplianceUpgradesDefault) Code() int {
	return o._statusCode
}

func (o *GetApplianceUpgradesDefault) Error() string {
	return fmt.Sprintf("[GET /appliance/Upgrades][%d] GetApplianceUpgrades default  %+v", o._statusCode, o.Payload)
}

func (o *GetApplianceUpgradesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplianceUpgradesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
