// Code generated by go-swagger; DO NOT EDIT.

package appliance_backup_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPostApplianceBackupPoliciesMoidParams creates a new PostApplianceBackupPoliciesMoidParams object
// with the default values initialized.
func NewPostApplianceBackupPoliciesMoidParams() *PostApplianceBackupPoliciesMoidParams {
	var ()
	return &PostApplianceBackupPoliciesMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostApplianceBackupPoliciesMoidParamsWithTimeout creates a new PostApplianceBackupPoliciesMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostApplianceBackupPoliciesMoidParamsWithTimeout(timeout time.Duration) *PostApplianceBackupPoliciesMoidParams {
	var ()
	return &PostApplianceBackupPoliciesMoidParams{

		timeout: timeout,
	}
}

// NewPostApplianceBackupPoliciesMoidParamsWithContext creates a new PostApplianceBackupPoliciesMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostApplianceBackupPoliciesMoidParamsWithContext(ctx context.Context) *PostApplianceBackupPoliciesMoidParams {
	var ()
	return &PostApplianceBackupPoliciesMoidParams{

		Context: ctx,
	}
}

// NewPostApplianceBackupPoliciesMoidParamsWithHTTPClient creates a new PostApplianceBackupPoliciesMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostApplianceBackupPoliciesMoidParamsWithHTTPClient(client *http.Client) *PostApplianceBackupPoliciesMoidParams {
	var ()
	return &PostApplianceBackupPoliciesMoidParams{
		HTTPClient: client,
	}
}

/*PostApplianceBackupPoliciesMoidParams contains all the parameters to send to the API endpoint
for the post appliance backup policies moid operation typically these are written to a http.Request
*/
type PostApplianceBackupPoliciesMoidParams struct {

	/*Body
	  applianceBackupPolicy to update

	*/
	Body *models.ApplianceBackupPolicy
	/*Moid
	  The moid of the applianceBackupPolicy instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post appliance backup policies moid params
func (o *PostApplianceBackupPoliciesMoidParams) WithTimeout(timeout time.Duration) *PostApplianceBackupPoliciesMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post appliance backup policies moid params
func (o *PostApplianceBackupPoliciesMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post appliance backup policies moid params
func (o *PostApplianceBackupPoliciesMoidParams) WithContext(ctx context.Context) *PostApplianceBackupPoliciesMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post appliance backup policies moid params
func (o *PostApplianceBackupPoliciesMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post appliance backup policies moid params
func (o *PostApplianceBackupPoliciesMoidParams) WithHTTPClient(client *http.Client) *PostApplianceBackupPoliciesMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post appliance backup policies moid params
func (o *PostApplianceBackupPoliciesMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post appliance backup policies moid params
func (o *PostApplianceBackupPoliciesMoidParams) WithBody(body *models.ApplianceBackupPolicy) *PostApplianceBackupPoliciesMoidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post appliance backup policies moid params
func (o *PostApplianceBackupPoliciesMoidParams) SetBody(body *models.ApplianceBackupPolicy) {
	o.Body = body
}

// WithMoid adds the moid to the post appliance backup policies moid params
func (o *PostApplianceBackupPoliciesMoidParams) WithMoid(moid string) *PostApplianceBackupPoliciesMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the post appliance backup policies moid params
func (o *PostApplianceBackupPoliciesMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *PostApplianceBackupPoliciesMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
