// Code generated by go-swagger; DO NOT EDIT.

package kvm_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PatchKvmPoliciesMoidReader is a Reader for the PatchKvmPoliciesMoid structure.
type PatchKvmPoliciesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchKvmPoliciesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPatchKvmPoliciesMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPatchKvmPoliciesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPatchKvmPoliciesMoidCreated creates a PatchKvmPoliciesMoidCreated with default headers values
func NewPatchKvmPoliciesMoidCreated() *PatchKvmPoliciesMoidCreated {
	return &PatchKvmPoliciesMoidCreated{}
}

/*PatchKvmPoliciesMoidCreated handles this case with default header values.

Null response
*/
type PatchKvmPoliciesMoidCreated struct {
}

func (o *PatchKvmPoliciesMoidCreated) Error() string {
	return fmt.Sprintf("[PATCH /kvm/Policies/{moid}][%d] patchKvmPoliciesMoidCreated ", 201)
}

func (o *PatchKvmPoliciesMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchKvmPoliciesMoidDefault creates a PatchKvmPoliciesMoidDefault with default headers values
func NewPatchKvmPoliciesMoidDefault(code int) *PatchKvmPoliciesMoidDefault {
	return &PatchKvmPoliciesMoidDefault{
		_statusCode: code,
	}
}

/*PatchKvmPoliciesMoidDefault handles this case with default header values.

unexpected error
*/
type PatchKvmPoliciesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the patch kvm policies moid default response
func (o *PatchKvmPoliciesMoidDefault) Code() int {
	return o._statusCode
}

func (o *PatchKvmPoliciesMoidDefault) Error() string {
	return fmt.Sprintf("[PATCH /kvm/Policies/{moid}][%d] PatchKvmPoliciesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PatchKvmPoliciesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchKvmPoliciesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
