// Code generated by go-swagger; DO NOT EDIT.

package kvm_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PostKvmPoliciesMoidReader is a Reader for the PostKvmPoliciesMoid structure.
type PostKvmPoliciesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostKvmPoliciesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostKvmPoliciesMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostKvmPoliciesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostKvmPoliciesMoidCreated creates a PostKvmPoliciesMoidCreated with default headers values
func NewPostKvmPoliciesMoidCreated() *PostKvmPoliciesMoidCreated {
	return &PostKvmPoliciesMoidCreated{}
}

/*PostKvmPoliciesMoidCreated handles this case with default header values.

Null response
*/
type PostKvmPoliciesMoidCreated struct {
}

func (o *PostKvmPoliciesMoidCreated) Error() string {
	return fmt.Sprintf("[POST /kvm/Policies/{moid}][%d] postKvmPoliciesMoidCreated ", 201)
}

func (o *PostKvmPoliciesMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostKvmPoliciesMoidDefault creates a PostKvmPoliciesMoidDefault with default headers values
func NewPostKvmPoliciesMoidDefault(code int) *PostKvmPoliciesMoidDefault {
	return &PostKvmPoliciesMoidDefault{
		_statusCode: code,
	}
}

/*PostKvmPoliciesMoidDefault handles this case with default header values.

unexpected error
*/
type PostKvmPoliciesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post kvm policies moid default response
func (o *PostKvmPoliciesMoidDefault) Code() int {
	return o._statusCode
}

func (o *PostKvmPoliciesMoidDefault) Error() string {
	return fmt.Sprintf("[POST /kvm/Policies/{moid}][%d] PostKvmPoliciesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PostKvmPoliciesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostKvmPoliciesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
