// Code generated by go-swagger; DO NOT EDIT.

package equipment_fex

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PatchEquipmentFexesMoidReader is a Reader for the PatchEquipmentFexesMoid structure.
type PatchEquipmentFexesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchEquipmentFexesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPatchEquipmentFexesMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPatchEquipmentFexesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPatchEquipmentFexesMoidCreated creates a PatchEquipmentFexesMoidCreated with default headers values
func NewPatchEquipmentFexesMoidCreated() *PatchEquipmentFexesMoidCreated {
	return &PatchEquipmentFexesMoidCreated{}
}

/*PatchEquipmentFexesMoidCreated handles this case with default header values.

Null response
*/
type PatchEquipmentFexesMoidCreated struct {
}

func (o *PatchEquipmentFexesMoidCreated) Error() string {
	return fmt.Sprintf("[PATCH /equipment/Fexes/{moid}][%d] patchEquipmentFexesMoidCreated ", 201)
}

func (o *PatchEquipmentFexesMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchEquipmentFexesMoidDefault creates a PatchEquipmentFexesMoidDefault with default headers values
func NewPatchEquipmentFexesMoidDefault(code int) *PatchEquipmentFexesMoidDefault {
	return &PatchEquipmentFexesMoidDefault{
		_statusCode: code,
	}
}

/*PatchEquipmentFexesMoidDefault handles this case with default header values.

unexpected error
*/
type PatchEquipmentFexesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the patch equipment fexes moid default response
func (o *PatchEquipmentFexesMoidDefault) Code() int {
	return o._statusCode
}

func (o *PatchEquipmentFexesMoidDefault) Error() string {
	return fmt.Sprintf("[PATCH /equipment/Fexes/{moid}][%d] PatchEquipmentFexesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PatchEquipmentFexesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchEquipmentFexesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
