// Code generated by go-swagger; DO NOT EDIT.

package storage_flex_flash_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PatchStorageFlexFlashControllersMoidReader is a Reader for the PatchStorageFlexFlashControllersMoid structure.
type PatchStorageFlexFlashControllersMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchStorageFlexFlashControllersMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPatchStorageFlexFlashControllersMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPatchStorageFlexFlashControllersMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPatchStorageFlexFlashControllersMoidCreated creates a PatchStorageFlexFlashControllersMoidCreated with default headers values
func NewPatchStorageFlexFlashControllersMoidCreated() *PatchStorageFlexFlashControllersMoidCreated {
	return &PatchStorageFlexFlashControllersMoidCreated{}
}

/*PatchStorageFlexFlashControllersMoidCreated handles this case with default header values.

Null response
*/
type PatchStorageFlexFlashControllersMoidCreated struct {
}

func (o *PatchStorageFlexFlashControllersMoidCreated) Error() string {
	return fmt.Sprintf("[PATCH /storage/FlexFlashControllers/{moid}][%d] patchStorageFlexFlashControllersMoidCreated ", 201)
}

func (o *PatchStorageFlexFlashControllersMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchStorageFlexFlashControllersMoidDefault creates a PatchStorageFlexFlashControllersMoidDefault with default headers values
func NewPatchStorageFlexFlashControllersMoidDefault(code int) *PatchStorageFlexFlashControllersMoidDefault {
	return &PatchStorageFlexFlashControllersMoidDefault{
		_statusCode: code,
	}
}

/*PatchStorageFlexFlashControllersMoidDefault handles this case with default header values.

unexpected error
*/
type PatchStorageFlexFlashControllersMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the patch storage flex flash controllers moid default response
func (o *PatchStorageFlexFlashControllersMoidDefault) Code() int {
	return o._statusCode
}

func (o *PatchStorageFlexFlashControllersMoidDefault) Error() string {
	return fmt.Sprintf("[PATCH /storage/FlexFlashControllers/{moid}][%d] PatchStorageFlexFlashControllersMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PatchStorageFlexFlashControllersMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchStorageFlexFlashControllersMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
