// Code generated by go-swagger; DO NOT EDIT.

package workflow_workflow_definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PostWorkflowWorkflowDefinitionsReader is a Reader for the PostWorkflowWorkflowDefinitions structure.
type PostWorkflowWorkflowDefinitionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostWorkflowWorkflowDefinitionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostWorkflowWorkflowDefinitionsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostWorkflowWorkflowDefinitionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostWorkflowWorkflowDefinitionsCreated creates a PostWorkflowWorkflowDefinitionsCreated with default headers values
func NewPostWorkflowWorkflowDefinitionsCreated() *PostWorkflowWorkflowDefinitionsCreated {
	return &PostWorkflowWorkflowDefinitionsCreated{}
}

/*PostWorkflowWorkflowDefinitionsCreated handles this case with default header values.

Null response
*/
type PostWorkflowWorkflowDefinitionsCreated struct {
}

func (o *PostWorkflowWorkflowDefinitionsCreated) Error() string {
	return fmt.Sprintf("[POST /workflow/WorkflowDefinitions][%d] postWorkflowWorkflowDefinitionsCreated ", 201)
}

func (o *PostWorkflowWorkflowDefinitionsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostWorkflowWorkflowDefinitionsDefault creates a PostWorkflowWorkflowDefinitionsDefault with default headers values
func NewPostWorkflowWorkflowDefinitionsDefault(code int) *PostWorkflowWorkflowDefinitionsDefault {
	return &PostWorkflowWorkflowDefinitionsDefault{
		_statusCode: code,
	}
}

/*PostWorkflowWorkflowDefinitionsDefault handles this case with default header values.

unexpected error
*/
type PostWorkflowWorkflowDefinitionsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post workflow workflow definitions default response
func (o *PostWorkflowWorkflowDefinitionsDefault) Code() int {
	return o._statusCode
}

func (o *PostWorkflowWorkflowDefinitionsDefault) Error() string {
	return fmt.Sprintf("[POST /workflow/WorkflowDefinitions][%d] PostWorkflowWorkflowDefinitions default  %+v", o._statusCode, o.Payload)
}

func (o *PostWorkflowWorkflowDefinitionsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostWorkflowWorkflowDefinitionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
