// Code generated by go-swagger; DO NOT EDIT.

package storage_virtual_drive

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PostStorageVirtualDrivesMoidReader is a Reader for the PostStorageVirtualDrivesMoid structure.
type PostStorageVirtualDrivesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostStorageVirtualDrivesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostStorageVirtualDrivesMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostStorageVirtualDrivesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostStorageVirtualDrivesMoidCreated creates a PostStorageVirtualDrivesMoidCreated with default headers values
func NewPostStorageVirtualDrivesMoidCreated() *PostStorageVirtualDrivesMoidCreated {
	return &PostStorageVirtualDrivesMoidCreated{}
}

/*PostStorageVirtualDrivesMoidCreated handles this case with default header values.

Null response
*/
type PostStorageVirtualDrivesMoidCreated struct {
}

func (o *PostStorageVirtualDrivesMoidCreated) Error() string {
	return fmt.Sprintf("[POST /storage/VirtualDrives/{moid}][%d] postStorageVirtualDrivesMoidCreated ", 201)
}

func (o *PostStorageVirtualDrivesMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostStorageVirtualDrivesMoidDefault creates a PostStorageVirtualDrivesMoidDefault with default headers values
func NewPostStorageVirtualDrivesMoidDefault(code int) *PostStorageVirtualDrivesMoidDefault {
	return &PostStorageVirtualDrivesMoidDefault{
		_statusCode: code,
	}
}

/*PostStorageVirtualDrivesMoidDefault handles this case with default header values.

unexpected error
*/
type PostStorageVirtualDrivesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post storage virtual drives moid default response
func (o *PostStorageVirtualDrivesMoidDefault) Code() int {
	return o._statusCode
}

func (o *PostStorageVirtualDrivesMoidDefault) Error() string {
	return fmt.Sprintf("[POST /storage/VirtualDrives/{moid}][%d] PostStorageVirtualDrivesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PostStorageVirtualDrivesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostStorageVirtualDrivesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
