// Code generated by go-swagger; DO NOT EDIT.

package firmware_running_firmware

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPatchFirmwareRunningFirmwaresMoidParams creates a new PatchFirmwareRunningFirmwaresMoidParams object
// with the default values initialized.
func NewPatchFirmwareRunningFirmwaresMoidParams() *PatchFirmwareRunningFirmwaresMoidParams {
	var ()
	return &PatchFirmwareRunningFirmwaresMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchFirmwareRunningFirmwaresMoidParamsWithTimeout creates a new PatchFirmwareRunningFirmwaresMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchFirmwareRunningFirmwaresMoidParamsWithTimeout(timeout time.Duration) *PatchFirmwareRunningFirmwaresMoidParams {
	var ()
	return &PatchFirmwareRunningFirmwaresMoidParams{

		timeout: timeout,
	}
}

// NewPatchFirmwareRunningFirmwaresMoidParamsWithContext creates a new PatchFirmwareRunningFirmwaresMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchFirmwareRunningFirmwaresMoidParamsWithContext(ctx context.Context) *PatchFirmwareRunningFirmwaresMoidParams {
	var ()
	return &PatchFirmwareRunningFirmwaresMoidParams{

		Context: ctx,
	}
}

// NewPatchFirmwareRunningFirmwaresMoidParamsWithHTTPClient creates a new PatchFirmwareRunningFirmwaresMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchFirmwareRunningFirmwaresMoidParamsWithHTTPClient(client *http.Client) *PatchFirmwareRunningFirmwaresMoidParams {
	var ()
	return &PatchFirmwareRunningFirmwaresMoidParams{
		HTTPClient: client,
	}
}

/*PatchFirmwareRunningFirmwaresMoidParams contains all the parameters to send to the API endpoint
for the patch firmware running firmwares moid operation typically these are written to a http.Request
*/
type PatchFirmwareRunningFirmwaresMoidParams struct {

	/*Body
	  firmwareRunningFirmware to update

	*/
	Body *models.FirmwareRunningFirmware
	/*Moid
	  The moid of the firmwareRunningFirmware instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch firmware running firmwares moid params
func (o *PatchFirmwareRunningFirmwaresMoidParams) WithTimeout(timeout time.Duration) *PatchFirmwareRunningFirmwaresMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch firmware running firmwares moid params
func (o *PatchFirmwareRunningFirmwaresMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch firmware running firmwares moid params
func (o *PatchFirmwareRunningFirmwaresMoidParams) WithContext(ctx context.Context) *PatchFirmwareRunningFirmwaresMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch firmware running firmwares moid params
func (o *PatchFirmwareRunningFirmwaresMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch firmware running firmwares moid params
func (o *PatchFirmwareRunningFirmwaresMoidParams) WithHTTPClient(client *http.Client) *PatchFirmwareRunningFirmwaresMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch firmware running firmwares moid params
func (o *PatchFirmwareRunningFirmwaresMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch firmware running firmwares moid params
func (o *PatchFirmwareRunningFirmwaresMoidParams) WithBody(body *models.FirmwareRunningFirmware) *PatchFirmwareRunningFirmwaresMoidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch firmware running firmwares moid params
func (o *PatchFirmwareRunningFirmwaresMoidParams) SetBody(body *models.FirmwareRunningFirmware) {
	o.Body = body
}

// WithMoid adds the moid to the patch firmware running firmwares moid params
func (o *PatchFirmwareRunningFirmwaresMoidParams) WithMoid(moid string) *PatchFirmwareRunningFirmwaresMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the patch firmware running firmwares moid params
func (o *PatchFirmwareRunningFirmwaresMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *PatchFirmwareRunningFirmwaresMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
