// Code generated by go-swagger; DO NOT EDIT.

package ntp_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPostNtpPoliciesParams creates a new PostNtpPoliciesParams object
// with the default values initialized.
func NewPostNtpPoliciesParams() *PostNtpPoliciesParams {
	var ()
	return &PostNtpPoliciesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostNtpPoliciesParamsWithTimeout creates a new PostNtpPoliciesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostNtpPoliciesParamsWithTimeout(timeout time.Duration) *PostNtpPoliciesParams {
	var ()
	return &PostNtpPoliciesParams{

		timeout: timeout,
	}
}

// NewPostNtpPoliciesParamsWithContext creates a new PostNtpPoliciesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostNtpPoliciesParamsWithContext(ctx context.Context) *PostNtpPoliciesParams {
	var ()
	return &PostNtpPoliciesParams{

		Context: ctx,
	}
}

// NewPostNtpPoliciesParamsWithHTTPClient creates a new PostNtpPoliciesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostNtpPoliciesParamsWithHTTPClient(client *http.Client) *PostNtpPoliciesParams {
	var ()
	return &PostNtpPoliciesParams{
		HTTPClient: client,
	}
}

/*PostNtpPoliciesParams contains all the parameters to send to the API endpoint
for the post ntp policies operation typically these are written to a http.Request
*/
type PostNtpPoliciesParams struct {

	/*Body
	  ntpPolicy to add

	*/
	Body *models.NtpPolicy

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post ntp policies params
func (o *PostNtpPoliciesParams) WithTimeout(timeout time.Duration) *PostNtpPoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post ntp policies params
func (o *PostNtpPoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post ntp policies params
func (o *PostNtpPoliciesParams) WithContext(ctx context.Context) *PostNtpPoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post ntp policies params
func (o *PostNtpPoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post ntp policies params
func (o *PostNtpPoliciesParams) WithHTTPClient(client *http.Client) *PostNtpPoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post ntp policies params
func (o *PostNtpPoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post ntp policies params
func (o *PostNtpPoliciesParams) WithBody(body *models.NtpPolicy) *PostNtpPoliciesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post ntp policies params
func (o *PostNtpPoliciesParams) SetBody(body *models.NtpPolicy) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostNtpPoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
