// Code generated by go-swagger; DO NOT EDIT.

package hyperflex_sys_config_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHyperflexSysConfigPoliciesMoidParams creates a new GetHyperflexSysConfigPoliciesMoidParams object
// with the default values initialized.
func NewGetHyperflexSysConfigPoliciesMoidParams() *GetHyperflexSysConfigPoliciesMoidParams {
	var ()
	return &GetHyperflexSysConfigPoliciesMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHyperflexSysConfigPoliciesMoidParamsWithTimeout creates a new GetHyperflexSysConfigPoliciesMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHyperflexSysConfigPoliciesMoidParamsWithTimeout(timeout time.Duration) *GetHyperflexSysConfigPoliciesMoidParams {
	var ()
	return &GetHyperflexSysConfigPoliciesMoidParams{

		timeout: timeout,
	}
}

// NewGetHyperflexSysConfigPoliciesMoidParamsWithContext creates a new GetHyperflexSysConfigPoliciesMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHyperflexSysConfigPoliciesMoidParamsWithContext(ctx context.Context) *GetHyperflexSysConfigPoliciesMoidParams {
	var ()
	return &GetHyperflexSysConfigPoliciesMoidParams{

		Context: ctx,
	}
}

// NewGetHyperflexSysConfigPoliciesMoidParamsWithHTTPClient creates a new GetHyperflexSysConfigPoliciesMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHyperflexSysConfigPoliciesMoidParamsWithHTTPClient(client *http.Client) *GetHyperflexSysConfigPoliciesMoidParams {
	var ()
	return &GetHyperflexSysConfigPoliciesMoidParams{
		HTTPClient: client,
	}
}

/*GetHyperflexSysConfigPoliciesMoidParams contains all the parameters to send to the API endpoint
for the get hyperflex sys config policies moid operation typically these are written to a http.Request
*/
type GetHyperflexSysConfigPoliciesMoidParams struct {

	/*Moid
	  The moid of the hyperflexSysConfigPolicy instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get hyperflex sys config policies moid params
func (o *GetHyperflexSysConfigPoliciesMoidParams) WithTimeout(timeout time.Duration) *GetHyperflexSysConfigPoliciesMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get hyperflex sys config policies moid params
func (o *GetHyperflexSysConfigPoliciesMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get hyperflex sys config policies moid params
func (o *GetHyperflexSysConfigPoliciesMoidParams) WithContext(ctx context.Context) *GetHyperflexSysConfigPoliciesMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get hyperflex sys config policies moid params
func (o *GetHyperflexSysConfigPoliciesMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get hyperflex sys config policies moid params
func (o *GetHyperflexSysConfigPoliciesMoidParams) WithHTTPClient(client *http.Client) *GetHyperflexSysConfigPoliciesMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get hyperflex sys config policies moid params
func (o *GetHyperflexSysConfigPoliciesMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the get hyperflex sys config policies moid params
func (o *GetHyperflexSysConfigPoliciesMoidParams) WithMoid(moid string) *GetHyperflexSysConfigPoliciesMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the get hyperflex sys config policies moid params
func (o *GetHyperflexSysConfigPoliciesMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *GetHyperflexSysConfigPoliciesMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
