// Code generated by go-swagger; DO NOT EDIT.

package iam_user_preference

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPatchIamUserPreferencesMoidParams creates a new PatchIamUserPreferencesMoidParams object
// with the default values initialized.
func NewPatchIamUserPreferencesMoidParams() *PatchIamUserPreferencesMoidParams {
	var ()
	return &PatchIamUserPreferencesMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchIamUserPreferencesMoidParamsWithTimeout creates a new PatchIamUserPreferencesMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchIamUserPreferencesMoidParamsWithTimeout(timeout time.Duration) *PatchIamUserPreferencesMoidParams {
	var ()
	return &PatchIamUserPreferencesMoidParams{

		timeout: timeout,
	}
}

// NewPatchIamUserPreferencesMoidParamsWithContext creates a new PatchIamUserPreferencesMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchIamUserPreferencesMoidParamsWithContext(ctx context.Context) *PatchIamUserPreferencesMoidParams {
	var ()
	return &PatchIamUserPreferencesMoidParams{

		Context: ctx,
	}
}

// NewPatchIamUserPreferencesMoidParamsWithHTTPClient creates a new PatchIamUserPreferencesMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchIamUserPreferencesMoidParamsWithHTTPClient(client *http.Client) *PatchIamUserPreferencesMoidParams {
	var ()
	return &PatchIamUserPreferencesMoidParams{
		HTTPClient: client,
	}
}

/*PatchIamUserPreferencesMoidParams contains all the parameters to send to the API endpoint
for the patch iam user preferences moid operation typically these are written to a http.Request
*/
type PatchIamUserPreferencesMoidParams struct {

	/*Body
	  iamUserPreference to update

	*/
	Body *models.IamUserPreference
	/*Moid
	  The moid of the iamUserPreference instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch iam user preferences moid params
func (o *PatchIamUserPreferencesMoidParams) WithTimeout(timeout time.Duration) *PatchIamUserPreferencesMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch iam user preferences moid params
func (o *PatchIamUserPreferencesMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch iam user preferences moid params
func (o *PatchIamUserPreferencesMoidParams) WithContext(ctx context.Context) *PatchIamUserPreferencesMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch iam user preferences moid params
func (o *PatchIamUserPreferencesMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch iam user preferences moid params
func (o *PatchIamUserPreferencesMoidParams) WithHTTPClient(client *http.Client) *PatchIamUserPreferencesMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch iam user preferences moid params
func (o *PatchIamUserPreferencesMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch iam user preferences moid params
func (o *PatchIamUserPreferencesMoidParams) WithBody(body *models.IamUserPreference) *PatchIamUserPreferencesMoidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch iam user preferences moid params
func (o *PatchIamUserPreferencesMoidParams) SetBody(body *models.IamUserPreference) {
	o.Body = body
}

// WithMoid adds the moid to the patch iam user preferences moid params
func (o *PatchIamUserPreferencesMoidParams) WithMoid(moid string) *PatchIamUserPreferencesMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the patch iam user preferences moid params
func (o *PatchIamUserPreferencesMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *PatchIamUserPreferencesMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
