// Code generated by go-swagger; DO NOT EDIT.

package network_element

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPatchNetworkElementsMoidParams creates a new PatchNetworkElementsMoidParams object
// with the default values initialized.
func NewPatchNetworkElementsMoidParams() *PatchNetworkElementsMoidParams {
	var ()
	return &PatchNetworkElementsMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchNetworkElementsMoidParamsWithTimeout creates a new PatchNetworkElementsMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchNetworkElementsMoidParamsWithTimeout(timeout time.Duration) *PatchNetworkElementsMoidParams {
	var ()
	return &PatchNetworkElementsMoidParams{

		timeout: timeout,
	}
}

// NewPatchNetworkElementsMoidParamsWithContext creates a new PatchNetworkElementsMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchNetworkElementsMoidParamsWithContext(ctx context.Context) *PatchNetworkElementsMoidParams {
	var ()
	return &PatchNetworkElementsMoidParams{

		Context: ctx,
	}
}

// NewPatchNetworkElementsMoidParamsWithHTTPClient creates a new PatchNetworkElementsMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchNetworkElementsMoidParamsWithHTTPClient(client *http.Client) *PatchNetworkElementsMoidParams {
	var ()
	return &PatchNetworkElementsMoidParams{
		HTTPClient: client,
	}
}

/*PatchNetworkElementsMoidParams contains all the parameters to send to the API endpoint
for the patch network elements moid operation typically these are written to a http.Request
*/
type PatchNetworkElementsMoidParams struct {

	/*Body
	  networkElement to update

	*/
	Body *models.NetworkElement
	/*Moid
	  The moid of the networkElement instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch network elements moid params
func (o *PatchNetworkElementsMoidParams) WithTimeout(timeout time.Duration) *PatchNetworkElementsMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch network elements moid params
func (o *PatchNetworkElementsMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch network elements moid params
func (o *PatchNetworkElementsMoidParams) WithContext(ctx context.Context) *PatchNetworkElementsMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch network elements moid params
func (o *PatchNetworkElementsMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch network elements moid params
func (o *PatchNetworkElementsMoidParams) WithHTTPClient(client *http.Client) *PatchNetworkElementsMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch network elements moid params
func (o *PatchNetworkElementsMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch network elements moid params
func (o *PatchNetworkElementsMoidParams) WithBody(body *models.NetworkElement) *PatchNetworkElementsMoidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch network elements moid params
func (o *PatchNetworkElementsMoidParams) SetBody(body *models.NetworkElement) {
	o.Body = body
}

// WithMoid adds the moid to the patch network elements moid params
func (o *PatchNetworkElementsMoidParams) WithMoid(moid string) *PatchNetworkElementsMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the patch network elements moid params
func (o *PatchNetworkElementsMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *PatchNetworkElementsMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
