// Code generated by go-swagger; DO NOT EDIT.

package server_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PostServerProfilesMoidReader is a Reader for the PostServerProfilesMoid structure.
type PostServerProfilesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostServerProfilesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostServerProfilesMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostServerProfilesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostServerProfilesMoidCreated creates a PostServerProfilesMoidCreated with default headers values
func NewPostServerProfilesMoidCreated() *PostServerProfilesMoidCreated {
	return &PostServerProfilesMoidCreated{}
}

/*PostServerProfilesMoidCreated handles this case with default header values.

Null response
*/
type PostServerProfilesMoidCreated struct {
}

func (o *PostServerProfilesMoidCreated) Error() string {
	return fmt.Sprintf("[POST /server/Profiles/{moid}][%d] postServerProfilesMoidCreated ", 201)
}

func (o *PostServerProfilesMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostServerProfilesMoidDefault creates a PostServerProfilesMoidDefault with default headers values
func NewPostServerProfilesMoidDefault(code int) *PostServerProfilesMoidDefault {
	return &PostServerProfilesMoidDefault{
		_statusCode: code,
	}
}

/*PostServerProfilesMoidDefault handles this case with default header values.

unexpected error
*/
type PostServerProfilesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post server profiles moid default response
func (o *PostServerProfilesMoidDefault) Code() int {
	return o._statusCode
}

func (o *PostServerProfilesMoidDefault) Error() string {
	return fmt.Sprintf("[POST /server/Profiles/{moid}][%d] PostServerProfilesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PostServerProfilesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostServerProfilesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
