// Code generated by go-swagger; DO NOT EDIT.

package iam_ldap_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PostIamLdapPoliciesReader is a Reader for the PostIamLdapPolicies structure.
type PostIamLdapPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIamLdapPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostIamLdapPoliciesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostIamLdapPoliciesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostIamLdapPoliciesCreated creates a PostIamLdapPoliciesCreated with default headers values
func NewPostIamLdapPoliciesCreated() *PostIamLdapPoliciesCreated {
	return &PostIamLdapPoliciesCreated{}
}

/*PostIamLdapPoliciesCreated handles this case with default header values.

Null response
*/
type PostIamLdapPoliciesCreated struct {
}

func (o *PostIamLdapPoliciesCreated) Error() string {
	return fmt.Sprintf("[POST /iam/LdapPolicies][%d] postIamLdapPoliciesCreated ", 201)
}

func (o *PostIamLdapPoliciesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostIamLdapPoliciesDefault creates a PostIamLdapPoliciesDefault with default headers values
func NewPostIamLdapPoliciesDefault(code int) *PostIamLdapPoliciesDefault {
	return &PostIamLdapPoliciesDefault{
		_statusCode: code,
	}
}

/*PostIamLdapPoliciesDefault handles this case with default header values.

unexpected error
*/
type PostIamLdapPoliciesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post iam ldap policies default response
func (o *PostIamLdapPoliciesDefault) Code() int {
	return o._statusCode
}

func (o *PostIamLdapPoliciesDefault) Error() string {
	return fmt.Sprintf("[POST /iam/LdapPolicies][%d] PostIamLdapPolicies default  %+v", o._statusCode, o.Payload)
}

func (o *PostIamLdapPoliciesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostIamLdapPoliciesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
