// Code generated by go-swagger; DO NOT EDIT.

package vmedia_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteVmediaPoliciesMoidParams creates a new DeleteVmediaPoliciesMoidParams object
// with the default values initialized.
func NewDeleteVmediaPoliciesMoidParams() *DeleteVmediaPoliciesMoidParams {
	var ()
	return &DeleteVmediaPoliciesMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVmediaPoliciesMoidParamsWithTimeout creates a new DeleteVmediaPoliciesMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteVmediaPoliciesMoidParamsWithTimeout(timeout time.Duration) *DeleteVmediaPoliciesMoidParams {
	var ()
	return &DeleteVmediaPoliciesMoidParams{

		timeout: timeout,
	}
}

// NewDeleteVmediaPoliciesMoidParamsWithContext creates a new DeleteVmediaPoliciesMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteVmediaPoliciesMoidParamsWithContext(ctx context.Context) *DeleteVmediaPoliciesMoidParams {
	var ()
	return &DeleteVmediaPoliciesMoidParams{

		Context: ctx,
	}
}

// NewDeleteVmediaPoliciesMoidParamsWithHTTPClient creates a new DeleteVmediaPoliciesMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteVmediaPoliciesMoidParamsWithHTTPClient(client *http.Client) *DeleteVmediaPoliciesMoidParams {
	var ()
	return &DeleteVmediaPoliciesMoidParams{
		HTTPClient: client,
	}
}

/*DeleteVmediaPoliciesMoidParams contains all the parameters to send to the API endpoint
for the delete vmedia policies moid operation typically these are written to a http.Request
*/
type DeleteVmediaPoliciesMoidParams struct {

	/*Moid
	  The moid of the vmediaPolicy instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete vmedia policies moid params
func (o *DeleteVmediaPoliciesMoidParams) WithTimeout(timeout time.Duration) *DeleteVmediaPoliciesMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete vmedia policies moid params
func (o *DeleteVmediaPoliciesMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete vmedia policies moid params
func (o *DeleteVmediaPoliciesMoidParams) WithContext(ctx context.Context) *DeleteVmediaPoliciesMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete vmedia policies moid params
func (o *DeleteVmediaPoliciesMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete vmedia policies moid params
func (o *DeleteVmediaPoliciesMoidParams) WithHTTPClient(client *http.Client) *DeleteVmediaPoliciesMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete vmedia policies moid params
func (o *DeleteVmediaPoliciesMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the delete vmedia policies moid params
func (o *DeleteVmediaPoliciesMoidParams) WithMoid(moid string) *DeleteVmediaPoliciesMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the delete vmedia policies moid params
func (o *DeleteVmediaPoliciesMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVmediaPoliciesMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
