// Code generated by go-swagger; DO NOT EDIT.

package storage_disk_group_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPatchStorageDiskGroupPoliciesMoidParams creates a new PatchStorageDiskGroupPoliciesMoidParams object
// with the default values initialized.
func NewPatchStorageDiskGroupPoliciesMoidParams() *PatchStorageDiskGroupPoliciesMoidParams {
	var ()
	return &PatchStorageDiskGroupPoliciesMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchStorageDiskGroupPoliciesMoidParamsWithTimeout creates a new PatchStorageDiskGroupPoliciesMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchStorageDiskGroupPoliciesMoidParamsWithTimeout(timeout time.Duration) *PatchStorageDiskGroupPoliciesMoidParams {
	var ()
	return &PatchStorageDiskGroupPoliciesMoidParams{

		timeout: timeout,
	}
}

// NewPatchStorageDiskGroupPoliciesMoidParamsWithContext creates a new PatchStorageDiskGroupPoliciesMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchStorageDiskGroupPoliciesMoidParamsWithContext(ctx context.Context) *PatchStorageDiskGroupPoliciesMoidParams {
	var ()
	return &PatchStorageDiskGroupPoliciesMoidParams{

		Context: ctx,
	}
}

// NewPatchStorageDiskGroupPoliciesMoidParamsWithHTTPClient creates a new PatchStorageDiskGroupPoliciesMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchStorageDiskGroupPoliciesMoidParamsWithHTTPClient(client *http.Client) *PatchStorageDiskGroupPoliciesMoidParams {
	var ()
	return &PatchStorageDiskGroupPoliciesMoidParams{
		HTTPClient: client,
	}
}

/*PatchStorageDiskGroupPoliciesMoidParams contains all the parameters to send to the API endpoint
for the patch storage disk group policies moid operation typically these are written to a http.Request
*/
type PatchStorageDiskGroupPoliciesMoidParams struct {

	/*Body
	  storageDiskGroupPolicy to update

	*/
	Body *models.StorageDiskGroupPolicy
	/*Moid
	  The moid of the storageDiskGroupPolicy instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch storage disk group policies moid params
func (o *PatchStorageDiskGroupPoliciesMoidParams) WithTimeout(timeout time.Duration) *PatchStorageDiskGroupPoliciesMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch storage disk group policies moid params
func (o *PatchStorageDiskGroupPoliciesMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch storage disk group policies moid params
func (o *PatchStorageDiskGroupPoliciesMoidParams) WithContext(ctx context.Context) *PatchStorageDiskGroupPoliciesMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch storage disk group policies moid params
func (o *PatchStorageDiskGroupPoliciesMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch storage disk group policies moid params
func (o *PatchStorageDiskGroupPoliciesMoidParams) WithHTTPClient(client *http.Client) *PatchStorageDiskGroupPoliciesMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch storage disk group policies moid params
func (o *PatchStorageDiskGroupPoliciesMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch storage disk group policies moid params
func (o *PatchStorageDiskGroupPoliciesMoidParams) WithBody(body *models.StorageDiskGroupPolicy) *PatchStorageDiskGroupPoliciesMoidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch storage disk group policies moid params
func (o *PatchStorageDiskGroupPoliciesMoidParams) SetBody(body *models.StorageDiskGroupPolicy) {
	o.Body = body
}

// WithMoid adds the moid to the patch storage disk group policies moid params
func (o *PatchStorageDiskGroupPoliciesMoidParams) WithMoid(moid string) *PatchStorageDiskGroupPoliciesMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the patch storage disk group policies moid params
func (o *PatchStorageDiskGroupPoliciesMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *PatchStorageDiskGroupPoliciesMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
