// Code generated by go-swagger; DO NOT EDIT.

package vnic_eth_network_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// GetVnicEthNetworkPoliciesMoidReader is a Reader for the GetVnicEthNetworkPoliciesMoid structure.
type GetVnicEthNetworkPoliciesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVnicEthNetworkPoliciesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVnicEthNetworkPoliciesMoidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetVnicEthNetworkPoliciesMoidNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetVnicEthNetworkPoliciesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetVnicEthNetworkPoliciesMoidOK creates a GetVnicEthNetworkPoliciesMoidOK with default headers values
func NewGetVnicEthNetworkPoliciesMoidOK() *GetVnicEthNetworkPoliciesMoidOK {
	return &GetVnicEthNetworkPoliciesMoidOK{}
}

/*GetVnicEthNetworkPoliciesMoidOK handles this case with default header values.

An instance of vnicEthNetworkPolicy
*/
type GetVnicEthNetworkPoliciesMoidOK struct {
	Payload *models.VnicEthNetworkPolicy
}

func (o *GetVnicEthNetworkPoliciesMoidOK) Error() string {
	return fmt.Sprintf("[GET /vnic/EthNetworkPolicies/{moid}][%d] getVnicEthNetworkPoliciesMoidOK  %+v", 200, o.Payload)
}

func (o *GetVnicEthNetworkPoliciesMoidOK) GetPayload() *models.VnicEthNetworkPolicy {
	return o.Payload
}

func (o *GetVnicEthNetworkPoliciesMoidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VnicEthNetworkPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVnicEthNetworkPoliciesMoidNotFound creates a GetVnicEthNetworkPoliciesMoidNotFound with default headers values
func NewGetVnicEthNetworkPoliciesMoidNotFound() *GetVnicEthNetworkPoliciesMoidNotFound {
	return &GetVnicEthNetworkPoliciesMoidNotFound{}
}

/*GetVnicEthNetworkPoliciesMoidNotFound handles this case with default header values.

Instance not found.
*/
type GetVnicEthNetworkPoliciesMoidNotFound struct {
}

func (o *GetVnicEthNetworkPoliciesMoidNotFound) Error() string {
	return fmt.Sprintf("[GET /vnic/EthNetworkPolicies/{moid}][%d] getVnicEthNetworkPoliciesMoidNotFound ", 404)
}

func (o *GetVnicEthNetworkPoliciesMoidNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetVnicEthNetworkPoliciesMoidDefault creates a GetVnicEthNetworkPoliciesMoidDefault with default headers values
func NewGetVnicEthNetworkPoliciesMoidDefault(code int) *GetVnicEthNetworkPoliciesMoidDefault {
	return &GetVnicEthNetworkPoliciesMoidDefault{
		_statusCode: code,
	}
}

/*GetVnicEthNetworkPoliciesMoidDefault handles this case with default header values.

Unexpected error
*/
type GetVnicEthNetworkPoliciesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get vnic eth network policies moid default response
func (o *GetVnicEthNetworkPoliciesMoidDefault) Code() int {
	return o._statusCode
}

func (o *GetVnicEthNetworkPoliciesMoidDefault) Error() string {
	return fmt.Sprintf("[GET /vnic/EthNetworkPolicies/{moid}][%d] GetVnicEthNetworkPoliciesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *GetVnicEthNetworkPoliciesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetVnicEthNetworkPoliciesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
