// Code generated by go-swagger; DO NOT EDIT.

package boot_precision_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// GetBootPrecisionPoliciesMoidReader is a Reader for the GetBootPrecisionPoliciesMoid structure.
type GetBootPrecisionPoliciesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBootPrecisionPoliciesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBootPrecisionPoliciesMoidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetBootPrecisionPoliciesMoidNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetBootPrecisionPoliciesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetBootPrecisionPoliciesMoidOK creates a GetBootPrecisionPoliciesMoidOK with default headers values
func NewGetBootPrecisionPoliciesMoidOK() *GetBootPrecisionPoliciesMoidOK {
	return &GetBootPrecisionPoliciesMoidOK{}
}

/*GetBootPrecisionPoliciesMoidOK handles this case with default header values.

An instance of bootPrecisionPolicy
*/
type GetBootPrecisionPoliciesMoidOK struct {
	Payload *models.BootPrecisionPolicy
}

func (o *GetBootPrecisionPoliciesMoidOK) Error() string {
	return fmt.Sprintf("[GET /boot/PrecisionPolicies/{moid}][%d] getBootPrecisionPoliciesMoidOK  %+v", 200, o.Payload)
}

func (o *GetBootPrecisionPoliciesMoidOK) GetPayload() *models.BootPrecisionPolicy {
	return o.Payload
}

func (o *GetBootPrecisionPoliciesMoidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BootPrecisionPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBootPrecisionPoliciesMoidNotFound creates a GetBootPrecisionPoliciesMoidNotFound with default headers values
func NewGetBootPrecisionPoliciesMoidNotFound() *GetBootPrecisionPoliciesMoidNotFound {
	return &GetBootPrecisionPoliciesMoidNotFound{}
}

/*GetBootPrecisionPoliciesMoidNotFound handles this case with default header values.

Instance not found.
*/
type GetBootPrecisionPoliciesMoidNotFound struct {
}

func (o *GetBootPrecisionPoliciesMoidNotFound) Error() string {
	return fmt.Sprintf("[GET /boot/PrecisionPolicies/{moid}][%d] getBootPrecisionPoliciesMoidNotFound ", 404)
}

func (o *GetBootPrecisionPoliciesMoidNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetBootPrecisionPoliciesMoidDefault creates a GetBootPrecisionPoliciesMoidDefault with default headers values
func NewGetBootPrecisionPoliciesMoidDefault(code int) *GetBootPrecisionPoliciesMoidDefault {
	return &GetBootPrecisionPoliciesMoidDefault{
		_statusCode: code,
	}
}

/*GetBootPrecisionPoliciesMoidDefault handles this case with default header values.

Unexpected error
*/
type GetBootPrecisionPoliciesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get boot precision policies moid default response
func (o *GetBootPrecisionPoliciesMoidDefault) Code() int {
	return o._statusCode
}

func (o *GetBootPrecisionPoliciesMoidDefault) Error() string {
	return fmt.Sprintf("[GET /boot/PrecisionPolicies/{moid}][%d] GetBootPrecisionPoliciesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *GetBootPrecisionPoliciesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBootPrecisionPoliciesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
