// Code generated by go-swagger; DO NOT EDIT.

package hyperflex_node_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// DeleteHyperflexNodeProfilesMoidReader is a Reader for the DeleteHyperflexNodeProfilesMoid structure.
type DeleteHyperflexNodeProfilesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteHyperflexNodeProfilesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteHyperflexNodeProfilesMoidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteHyperflexNodeProfilesMoidNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteHyperflexNodeProfilesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteHyperflexNodeProfilesMoidOK creates a DeleteHyperflexNodeProfilesMoidOK with default headers values
func NewDeleteHyperflexNodeProfilesMoidOK() *DeleteHyperflexNodeProfilesMoidOK {
	return &DeleteHyperflexNodeProfilesMoidOK{}
}

/*DeleteHyperflexNodeProfilesMoidOK handles this case with default header values.

Delete successful.
*/
type DeleteHyperflexNodeProfilesMoidOK struct {
}

func (o *DeleteHyperflexNodeProfilesMoidOK) Error() string {
	return fmt.Sprintf("[DELETE /hyperflex/NodeProfiles/{moid}][%d] deleteHyperflexNodeProfilesMoidOK ", 200)
}

func (o *DeleteHyperflexNodeProfilesMoidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteHyperflexNodeProfilesMoidNotFound creates a DeleteHyperflexNodeProfilesMoidNotFound with default headers values
func NewDeleteHyperflexNodeProfilesMoidNotFound() *DeleteHyperflexNodeProfilesMoidNotFound {
	return &DeleteHyperflexNodeProfilesMoidNotFound{}
}

/*DeleteHyperflexNodeProfilesMoidNotFound handles this case with default header values.

Instance not found.
*/
type DeleteHyperflexNodeProfilesMoidNotFound struct {
}

func (o *DeleteHyperflexNodeProfilesMoidNotFound) Error() string {
	return fmt.Sprintf("[DELETE /hyperflex/NodeProfiles/{moid}][%d] deleteHyperflexNodeProfilesMoidNotFound ", 404)
}

func (o *DeleteHyperflexNodeProfilesMoidNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteHyperflexNodeProfilesMoidDefault creates a DeleteHyperflexNodeProfilesMoidDefault with default headers values
func NewDeleteHyperflexNodeProfilesMoidDefault(code int) *DeleteHyperflexNodeProfilesMoidDefault {
	return &DeleteHyperflexNodeProfilesMoidDefault{
		_statusCode: code,
	}
}

/*DeleteHyperflexNodeProfilesMoidDefault handles this case with default header values.

Unexpected error
*/
type DeleteHyperflexNodeProfilesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete hyperflex node profiles moid default response
func (o *DeleteHyperflexNodeProfilesMoidDefault) Code() int {
	return o._statusCode
}

func (o *DeleteHyperflexNodeProfilesMoidDefault) Error() string {
	return fmt.Sprintf("[DELETE /hyperflex/NodeProfiles/{moid}][%d] DeleteHyperflexNodeProfilesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteHyperflexNodeProfilesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteHyperflexNodeProfilesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
