// Code generated by go-swagger; DO NOT EDIT.

package storage_virtual_drive_extension

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PatchStorageVirtualDriveExtensionsMoidReader is a Reader for the PatchStorageVirtualDriveExtensionsMoid structure.
type PatchStorageVirtualDriveExtensionsMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchStorageVirtualDriveExtensionsMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPatchStorageVirtualDriveExtensionsMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPatchStorageVirtualDriveExtensionsMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPatchStorageVirtualDriveExtensionsMoidCreated creates a PatchStorageVirtualDriveExtensionsMoidCreated with default headers values
func NewPatchStorageVirtualDriveExtensionsMoidCreated() *PatchStorageVirtualDriveExtensionsMoidCreated {
	return &PatchStorageVirtualDriveExtensionsMoidCreated{}
}

/*PatchStorageVirtualDriveExtensionsMoidCreated handles this case with default header values.

Null response
*/
type PatchStorageVirtualDriveExtensionsMoidCreated struct {
}

func (o *PatchStorageVirtualDriveExtensionsMoidCreated) Error() string {
	return fmt.Sprintf("[PATCH /storage/VirtualDriveExtensions/{moid}][%d] patchStorageVirtualDriveExtensionsMoidCreated ", 201)
}

func (o *PatchStorageVirtualDriveExtensionsMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchStorageVirtualDriveExtensionsMoidDefault creates a PatchStorageVirtualDriveExtensionsMoidDefault with default headers values
func NewPatchStorageVirtualDriveExtensionsMoidDefault(code int) *PatchStorageVirtualDriveExtensionsMoidDefault {
	return &PatchStorageVirtualDriveExtensionsMoidDefault{
		_statusCode: code,
	}
}

/*PatchStorageVirtualDriveExtensionsMoidDefault handles this case with default header values.

unexpected error
*/
type PatchStorageVirtualDriveExtensionsMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the patch storage virtual drive extensions moid default response
func (o *PatchStorageVirtualDriveExtensionsMoidDefault) Code() int {
	return o._statusCode
}

func (o *PatchStorageVirtualDriveExtensionsMoidDefault) Error() string {
	return fmt.Sprintf("[PATCH /storage/VirtualDriveExtensions/{moid}][%d] PatchStorageVirtualDriveExtensionsMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PatchStorageVirtualDriveExtensionsMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchStorageVirtualDriveExtensionsMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
