// Code generated by go-swagger; DO NOT EDIT.

package storage_virtual_drive_extension

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPatchStorageVirtualDriveExtensionsMoidParams creates a new PatchStorageVirtualDriveExtensionsMoidParams object
// with the default values initialized.
func NewPatchStorageVirtualDriveExtensionsMoidParams() *PatchStorageVirtualDriveExtensionsMoidParams {
	var ()
	return &PatchStorageVirtualDriveExtensionsMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchStorageVirtualDriveExtensionsMoidParamsWithTimeout creates a new PatchStorageVirtualDriveExtensionsMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchStorageVirtualDriveExtensionsMoidParamsWithTimeout(timeout time.Duration) *PatchStorageVirtualDriveExtensionsMoidParams {
	var ()
	return &PatchStorageVirtualDriveExtensionsMoidParams{

		timeout: timeout,
	}
}

// NewPatchStorageVirtualDriveExtensionsMoidParamsWithContext creates a new PatchStorageVirtualDriveExtensionsMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchStorageVirtualDriveExtensionsMoidParamsWithContext(ctx context.Context) *PatchStorageVirtualDriveExtensionsMoidParams {
	var ()
	return &PatchStorageVirtualDriveExtensionsMoidParams{

		Context: ctx,
	}
}

// NewPatchStorageVirtualDriveExtensionsMoidParamsWithHTTPClient creates a new PatchStorageVirtualDriveExtensionsMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchStorageVirtualDriveExtensionsMoidParamsWithHTTPClient(client *http.Client) *PatchStorageVirtualDriveExtensionsMoidParams {
	var ()
	return &PatchStorageVirtualDriveExtensionsMoidParams{
		HTTPClient: client,
	}
}

/*PatchStorageVirtualDriveExtensionsMoidParams contains all the parameters to send to the API endpoint
for the patch storage virtual drive extensions moid operation typically these are written to a http.Request
*/
type PatchStorageVirtualDriveExtensionsMoidParams struct {

	/*Body
	  storageVirtualDriveExtension to update

	*/
	Body *models.StorageVirtualDriveExtension
	/*Moid
	  The moid of the storageVirtualDriveExtension instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch storage virtual drive extensions moid params
func (o *PatchStorageVirtualDriveExtensionsMoidParams) WithTimeout(timeout time.Duration) *PatchStorageVirtualDriveExtensionsMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch storage virtual drive extensions moid params
func (o *PatchStorageVirtualDriveExtensionsMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch storage virtual drive extensions moid params
func (o *PatchStorageVirtualDriveExtensionsMoidParams) WithContext(ctx context.Context) *PatchStorageVirtualDriveExtensionsMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch storage virtual drive extensions moid params
func (o *PatchStorageVirtualDriveExtensionsMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch storage virtual drive extensions moid params
func (o *PatchStorageVirtualDriveExtensionsMoidParams) WithHTTPClient(client *http.Client) *PatchStorageVirtualDriveExtensionsMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch storage virtual drive extensions moid params
func (o *PatchStorageVirtualDriveExtensionsMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch storage virtual drive extensions moid params
func (o *PatchStorageVirtualDriveExtensionsMoidParams) WithBody(body *models.StorageVirtualDriveExtension) *PatchStorageVirtualDriveExtensionsMoidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch storage virtual drive extensions moid params
func (o *PatchStorageVirtualDriveExtensionsMoidParams) SetBody(body *models.StorageVirtualDriveExtension) {
	o.Body = body
}

// WithMoid adds the moid to the patch storage virtual drive extensions moid params
func (o *PatchStorageVirtualDriveExtensionsMoidParams) WithMoid(moid string) *PatchStorageVirtualDriveExtensionsMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the patch storage virtual drive extensions moid params
func (o *PatchStorageVirtualDriveExtensionsMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *PatchStorageVirtualDriveExtensionsMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
