// Code generated by go-swagger; DO NOT EDIT.

package vnic_san_connectivity_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PatchVnicSanConnectivityPoliciesMoidReader is a Reader for the PatchVnicSanConnectivityPoliciesMoid structure.
type PatchVnicSanConnectivityPoliciesMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchVnicSanConnectivityPoliciesMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPatchVnicSanConnectivityPoliciesMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPatchVnicSanConnectivityPoliciesMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPatchVnicSanConnectivityPoliciesMoidCreated creates a PatchVnicSanConnectivityPoliciesMoidCreated with default headers values
func NewPatchVnicSanConnectivityPoliciesMoidCreated() *PatchVnicSanConnectivityPoliciesMoidCreated {
	return &PatchVnicSanConnectivityPoliciesMoidCreated{}
}

/*PatchVnicSanConnectivityPoliciesMoidCreated handles this case with default header values.

Null response
*/
type PatchVnicSanConnectivityPoliciesMoidCreated struct {
}

func (o *PatchVnicSanConnectivityPoliciesMoidCreated) Error() string {
	return fmt.Sprintf("[PATCH /vnic/SanConnectivityPolicies/{moid}][%d] patchVnicSanConnectivityPoliciesMoidCreated ", 201)
}

func (o *PatchVnicSanConnectivityPoliciesMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchVnicSanConnectivityPoliciesMoidDefault creates a PatchVnicSanConnectivityPoliciesMoidDefault with default headers values
func NewPatchVnicSanConnectivityPoliciesMoidDefault(code int) *PatchVnicSanConnectivityPoliciesMoidDefault {
	return &PatchVnicSanConnectivityPoliciesMoidDefault{
		_statusCode: code,
	}
}

/*PatchVnicSanConnectivityPoliciesMoidDefault handles this case with default header values.

unexpected error
*/
type PatchVnicSanConnectivityPoliciesMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the patch vnic san connectivity policies moid default response
func (o *PatchVnicSanConnectivityPoliciesMoidDefault) Code() int {
	return o._statusCode
}

func (o *PatchVnicSanConnectivityPoliciesMoidDefault) Error() string {
	return fmt.Sprintf("[PATCH /vnic/SanConnectivityPolicies/{moid}][%d] PatchVnicSanConnectivityPoliciesMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PatchVnicSanConnectivityPoliciesMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchVnicSanConnectivityPoliciesMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
