// Code generated by go-swagger; DO NOT EDIT.

package iam_system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIamSystemsMoidParams creates a new GetIamSystemsMoidParams object
// with the default values initialized.
func NewGetIamSystemsMoidParams() *GetIamSystemsMoidParams {
	var ()
	return &GetIamSystemsMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIamSystemsMoidParamsWithTimeout creates a new GetIamSystemsMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIamSystemsMoidParamsWithTimeout(timeout time.Duration) *GetIamSystemsMoidParams {
	var ()
	return &GetIamSystemsMoidParams{

		timeout: timeout,
	}
}

// NewGetIamSystemsMoidParamsWithContext creates a new GetIamSystemsMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIamSystemsMoidParamsWithContext(ctx context.Context) *GetIamSystemsMoidParams {
	var ()
	return &GetIamSystemsMoidParams{

		Context: ctx,
	}
}

// NewGetIamSystemsMoidParamsWithHTTPClient creates a new GetIamSystemsMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIamSystemsMoidParamsWithHTTPClient(client *http.Client) *GetIamSystemsMoidParams {
	var ()
	return &GetIamSystemsMoidParams{
		HTTPClient: client,
	}
}

/*GetIamSystemsMoidParams contains all the parameters to send to the API endpoint
for the get iam systems moid operation typically these are written to a http.Request
*/
type GetIamSystemsMoidParams struct {

	/*Moid
	  The moid of the iamSystem instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get iam systems moid params
func (o *GetIamSystemsMoidParams) WithTimeout(timeout time.Duration) *GetIamSystemsMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get iam systems moid params
func (o *GetIamSystemsMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get iam systems moid params
func (o *GetIamSystemsMoidParams) WithContext(ctx context.Context) *GetIamSystemsMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get iam systems moid params
func (o *GetIamSystemsMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get iam systems moid params
func (o *GetIamSystemsMoidParams) WithHTTPClient(client *http.Client) *GetIamSystemsMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get iam systems moid params
func (o *GetIamSystemsMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the get iam systems moid params
func (o *GetIamSystemsMoidParams) WithMoid(moid string) *GetIamSystemsMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the get iam systems moid params
func (o *GetIamSystemsMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *GetIamSystemsMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
