// Code generated by go-swagger; DO NOT EDIT.

package compute_rack_unit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// GetComputeRackUnitsReader is a Reader for the GetComputeRackUnits structure.
type GetComputeRackUnitsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetComputeRackUnitsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetComputeRackUnitsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetComputeRackUnitsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetComputeRackUnitsOK creates a GetComputeRackUnitsOK with default headers values
func NewGetComputeRackUnitsOK() *GetComputeRackUnitsOK {
	return &GetComputeRackUnitsOK{}
}

/*GetComputeRackUnitsOK handles this case with default header values.

List of computeRackUnits for the given filter criteria
*/
type GetComputeRackUnitsOK struct {
	Payload *models.ComputeRackUnitList
}

func (o *GetComputeRackUnitsOK) Error() string {
	return fmt.Sprintf("[GET /compute/RackUnits][%d] getComputeRackUnitsOK  %+v", 200, o.Payload)
}

func (o *GetComputeRackUnitsOK) GetPayload() *models.ComputeRackUnitList {
	return o.Payload
}

func (o *GetComputeRackUnitsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComputeRackUnitList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComputeRackUnitsDefault creates a GetComputeRackUnitsDefault with default headers values
func NewGetComputeRackUnitsDefault(code int) *GetComputeRackUnitsDefault {
	return &GetComputeRackUnitsDefault{
		_statusCode: code,
	}
}

/*GetComputeRackUnitsDefault handles this case with default header values.

Unexpected error
*/
type GetComputeRackUnitsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get compute rack units default response
func (o *GetComputeRackUnitsDefault) Code() int {
	return o._statusCode
}

func (o *GetComputeRackUnitsDefault) Error() string {
	return fmt.Sprintf("[GET /compute/RackUnits][%d] GetComputeRackUnits default  %+v", o._statusCode, o.Payload)
}

func (o *GetComputeRackUnitsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetComputeRackUnitsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
