// Code generated by go-swagger; DO NOT EDIT.

package compute_rack_unit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPatchComputeRackUnitsMoidParams creates a new PatchComputeRackUnitsMoidParams object
// with the default values initialized.
func NewPatchComputeRackUnitsMoidParams() *PatchComputeRackUnitsMoidParams {
	var ()
	return &PatchComputeRackUnitsMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchComputeRackUnitsMoidParamsWithTimeout creates a new PatchComputeRackUnitsMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchComputeRackUnitsMoidParamsWithTimeout(timeout time.Duration) *PatchComputeRackUnitsMoidParams {
	var ()
	return &PatchComputeRackUnitsMoidParams{

		timeout: timeout,
	}
}

// NewPatchComputeRackUnitsMoidParamsWithContext creates a new PatchComputeRackUnitsMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchComputeRackUnitsMoidParamsWithContext(ctx context.Context) *PatchComputeRackUnitsMoidParams {
	var ()
	return &PatchComputeRackUnitsMoidParams{

		Context: ctx,
	}
}

// NewPatchComputeRackUnitsMoidParamsWithHTTPClient creates a new PatchComputeRackUnitsMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchComputeRackUnitsMoidParamsWithHTTPClient(client *http.Client) *PatchComputeRackUnitsMoidParams {
	var ()
	return &PatchComputeRackUnitsMoidParams{
		HTTPClient: client,
	}
}

/*PatchComputeRackUnitsMoidParams contains all the parameters to send to the API endpoint
for the patch compute rack units moid operation typically these are written to a http.Request
*/
type PatchComputeRackUnitsMoidParams struct {

	/*Body
	  computeRackUnit to update

	*/
	Body *models.ComputeRackUnit
	/*Moid
	  The moid of the computeRackUnit instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch compute rack units moid params
func (o *PatchComputeRackUnitsMoidParams) WithTimeout(timeout time.Duration) *PatchComputeRackUnitsMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch compute rack units moid params
func (o *PatchComputeRackUnitsMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch compute rack units moid params
func (o *PatchComputeRackUnitsMoidParams) WithContext(ctx context.Context) *PatchComputeRackUnitsMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch compute rack units moid params
func (o *PatchComputeRackUnitsMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch compute rack units moid params
func (o *PatchComputeRackUnitsMoidParams) WithHTTPClient(client *http.Client) *PatchComputeRackUnitsMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch compute rack units moid params
func (o *PatchComputeRackUnitsMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch compute rack units moid params
func (o *PatchComputeRackUnitsMoidParams) WithBody(body *models.ComputeRackUnit) *PatchComputeRackUnitsMoidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch compute rack units moid params
func (o *PatchComputeRackUnitsMoidParams) SetBody(body *models.ComputeRackUnit) {
	o.Body = body
}

// WithMoid adds the moid to the patch compute rack units moid params
func (o *PatchComputeRackUnitsMoidParams) WithMoid(moid string) *PatchComputeRackUnitsMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the patch compute rack units moid params
func (o *PatchComputeRackUnitsMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *PatchComputeRackUnitsMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
