// Code generated by go-swagger; DO NOT EDIT.

package workflow_batch_api_executor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPatchWorkflowBatchAPIExecutorsMoidParams creates a new PatchWorkflowBatchAPIExecutorsMoidParams object
// with the default values initialized.
func NewPatchWorkflowBatchAPIExecutorsMoidParams() *PatchWorkflowBatchAPIExecutorsMoidParams {
	var ()
	return &PatchWorkflowBatchAPIExecutorsMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchWorkflowBatchAPIExecutorsMoidParamsWithTimeout creates a new PatchWorkflowBatchAPIExecutorsMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchWorkflowBatchAPIExecutorsMoidParamsWithTimeout(timeout time.Duration) *PatchWorkflowBatchAPIExecutorsMoidParams {
	var ()
	return &PatchWorkflowBatchAPIExecutorsMoidParams{

		timeout: timeout,
	}
}

// NewPatchWorkflowBatchAPIExecutorsMoidParamsWithContext creates a new PatchWorkflowBatchAPIExecutorsMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchWorkflowBatchAPIExecutorsMoidParamsWithContext(ctx context.Context) *PatchWorkflowBatchAPIExecutorsMoidParams {
	var ()
	return &PatchWorkflowBatchAPIExecutorsMoidParams{

		Context: ctx,
	}
}

// NewPatchWorkflowBatchAPIExecutorsMoidParamsWithHTTPClient creates a new PatchWorkflowBatchAPIExecutorsMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchWorkflowBatchAPIExecutorsMoidParamsWithHTTPClient(client *http.Client) *PatchWorkflowBatchAPIExecutorsMoidParams {
	var ()
	return &PatchWorkflowBatchAPIExecutorsMoidParams{
		HTTPClient: client,
	}
}

/*PatchWorkflowBatchAPIExecutorsMoidParams contains all the parameters to send to the API endpoint
for the patch workflow batch API executors moid operation typically these are written to a http.Request
*/
type PatchWorkflowBatchAPIExecutorsMoidParams struct {

	/*Body
	  workflowBatchApiExecutor to update

	*/
	Body *models.WorkflowBatchAPIExecutor
	/*Moid
	  The moid of the workflowBatchApiExecutor instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch workflow batch API executors moid params
func (o *PatchWorkflowBatchAPIExecutorsMoidParams) WithTimeout(timeout time.Duration) *PatchWorkflowBatchAPIExecutorsMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch workflow batch API executors moid params
func (o *PatchWorkflowBatchAPIExecutorsMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch workflow batch API executors moid params
func (o *PatchWorkflowBatchAPIExecutorsMoidParams) WithContext(ctx context.Context) *PatchWorkflowBatchAPIExecutorsMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch workflow batch API executors moid params
func (o *PatchWorkflowBatchAPIExecutorsMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch workflow batch API executors moid params
func (o *PatchWorkflowBatchAPIExecutorsMoidParams) WithHTTPClient(client *http.Client) *PatchWorkflowBatchAPIExecutorsMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch workflow batch API executors moid params
func (o *PatchWorkflowBatchAPIExecutorsMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch workflow batch API executors moid params
func (o *PatchWorkflowBatchAPIExecutorsMoidParams) WithBody(body *models.WorkflowBatchAPIExecutor) *PatchWorkflowBatchAPIExecutorsMoidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch workflow batch API executors moid params
func (o *PatchWorkflowBatchAPIExecutorsMoidParams) SetBody(body *models.WorkflowBatchAPIExecutor) {
	o.Body = body
}

// WithMoid adds the moid to the patch workflow batch API executors moid params
func (o *PatchWorkflowBatchAPIExecutorsMoidParams) WithMoid(moid string) *PatchWorkflowBatchAPIExecutorsMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the patch workflow batch API executors moid params
func (o *PatchWorkflowBatchAPIExecutorsMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *PatchWorkflowBatchAPIExecutorsMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
