// Code generated by go-swagger; DO NOT EDIT.

package security_unit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// PostSecurityUnitsMoidReader is a Reader for the PostSecurityUnitsMoid structure.
type PostSecurityUnitsMoidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSecurityUnitsMoidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostSecurityUnitsMoidCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostSecurityUnitsMoidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostSecurityUnitsMoidCreated creates a PostSecurityUnitsMoidCreated with default headers values
func NewPostSecurityUnitsMoidCreated() *PostSecurityUnitsMoidCreated {
	return &PostSecurityUnitsMoidCreated{}
}

/*PostSecurityUnitsMoidCreated handles this case with default header values.

Null response
*/
type PostSecurityUnitsMoidCreated struct {
}

func (o *PostSecurityUnitsMoidCreated) Error() string {
	return fmt.Sprintf("[POST /security/Units/{moid}][%d] postSecurityUnitsMoidCreated ", 201)
}

func (o *PostSecurityUnitsMoidCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostSecurityUnitsMoidDefault creates a PostSecurityUnitsMoidDefault with default headers values
func NewPostSecurityUnitsMoidDefault(code int) *PostSecurityUnitsMoidDefault {
	return &PostSecurityUnitsMoidDefault{
		_statusCode: code,
	}
}

/*PostSecurityUnitsMoidDefault handles this case with default header values.

unexpected error
*/
type PostSecurityUnitsMoidDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post security units moid default response
func (o *PostSecurityUnitsMoidDefault) Code() int {
	return o._statusCode
}

func (o *PostSecurityUnitsMoidDefault) Error() string {
	return fmt.Sprintf("[POST /security/Units/{moid}][%d] PostSecurityUnitsMoid default  %+v", o._statusCode, o.Payload)
}

func (o *PostSecurityUnitsMoidDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostSecurityUnitsMoidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
