// Code generated by go-swagger; DO NOT EDIT.

package equipment_psu

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEquipmentPsusMoidParams creates a new GetEquipmentPsusMoidParams object
// with the default values initialized.
func NewGetEquipmentPsusMoidParams() *GetEquipmentPsusMoidParams {
	var ()
	return &GetEquipmentPsusMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEquipmentPsusMoidParamsWithTimeout creates a new GetEquipmentPsusMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEquipmentPsusMoidParamsWithTimeout(timeout time.Duration) *GetEquipmentPsusMoidParams {
	var ()
	return &GetEquipmentPsusMoidParams{

		timeout: timeout,
	}
}

// NewGetEquipmentPsusMoidParamsWithContext creates a new GetEquipmentPsusMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEquipmentPsusMoidParamsWithContext(ctx context.Context) *GetEquipmentPsusMoidParams {
	var ()
	return &GetEquipmentPsusMoidParams{

		Context: ctx,
	}
}

// NewGetEquipmentPsusMoidParamsWithHTTPClient creates a new GetEquipmentPsusMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEquipmentPsusMoidParamsWithHTTPClient(client *http.Client) *GetEquipmentPsusMoidParams {
	var ()
	return &GetEquipmentPsusMoidParams{
		HTTPClient: client,
	}
}

/*GetEquipmentPsusMoidParams contains all the parameters to send to the API endpoint
for the get equipment psus moid operation typically these are written to a http.Request
*/
type GetEquipmentPsusMoidParams struct {

	/*Moid
	  The moid of the equipmentPsu instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get equipment psus moid params
func (o *GetEquipmentPsusMoidParams) WithTimeout(timeout time.Duration) *GetEquipmentPsusMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get equipment psus moid params
func (o *GetEquipmentPsusMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get equipment psus moid params
func (o *GetEquipmentPsusMoidParams) WithContext(ctx context.Context) *GetEquipmentPsusMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get equipment psus moid params
func (o *GetEquipmentPsusMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get equipment psus moid params
func (o *GetEquipmentPsusMoidParams) WithHTTPClient(client *http.Client) *GetEquipmentPsusMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get equipment psus moid params
func (o *GetEquipmentPsusMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the get equipment psus moid params
func (o *GetEquipmentPsusMoidParams) WithMoid(moid string) *GetEquipmentPsusMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the get equipment psus moid params
func (o *GetEquipmentPsusMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *GetEquipmentPsusMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
