// Code generated by go-swagger; DO NOT EDIT.

package iam_trust_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIamTrustPointsMoidParams creates a new GetIamTrustPointsMoidParams object
// with the default values initialized.
func NewGetIamTrustPointsMoidParams() *GetIamTrustPointsMoidParams {
	var ()
	return &GetIamTrustPointsMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIamTrustPointsMoidParamsWithTimeout creates a new GetIamTrustPointsMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIamTrustPointsMoidParamsWithTimeout(timeout time.Duration) *GetIamTrustPointsMoidParams {
	var ()
	return &GetIamTrustPointsMoidParams{

		timeout: timeout,
	}
}

// NewGetIamTrustPointsMoidParamsWithContext creates a new GetIamTrustPointsMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIamTrustPointsMoidParamsWithContext(ctx context.Context) *GetIamTrustPointsMoidParams {
	var ()
	return &GetIamTrustPointsMoidParams{

		Context: ctx,
	}
}

// NewGetIamTrustPointsMoidParamsWithHTTPClient creates a new GetIamTrustPointsMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIamTrustPointsMoidParamsWithHTTPClient(client *http.Client) *GetIamTrustPointsMoidParams {
	var ()
	return &GetIamTrustPointsMoidParams{
		HTTPClient: client,
	}
}

/*GetIamTrustPointsMoidParams contains all the parameters to send to the API endpoint
for the get iam trust points moid operation typically these are written to a http.Request
*/
type GetIamTrustPointsMoidParams struct {

	/*Moid
	  The moid of the iamTrustPoint instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get iam trust points moid params
func (o *GetIamTrustPointsMoidParams) WithTimeout(timeout time.Duration) *GetIamTrustPointsMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get iam trust points moid params
func (o *GetIamTrustPointsMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get iam trust points moid params
func (o *GetIamTrustPointsMoidParams) WithContext(ctx context.Context) *GetIamTrustPointsMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get iam trust points moid params
func (o *GetIamTrustPointsMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get iam trust points moid params
func (o *GetIamTrustPointsMoidParams) WithHTTPClient(client *http.Client) *GetIamTrustPointsMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get iam trust points moid params
func (o *GetIamTrustPointsMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the get iam trust points moid params
func (o *GetIamTrustPointsMoidParams) WithMoid(moid string) *GetIamTrustPointsMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the get iam trust points moid params
func (o *GetIamTrustPointsMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *GetIamTrustPointsMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
