// Code generated by go-swagger; DO NOT EDIT.

package workflow_workflow_info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWorkflowWorkflowInfosMoidParams creates a new GetWorkflowWorkflowInfosMoidParams object
// with the default values initialized.
func NewGetWorkflowWorkflowInfosMoidParams() *GetWorkflowWorkflowInfosMoidParams {
	var ()
	return &GetWorkflowWorkflowInfosMoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkflowWorkflowInfosMoidParamsWithTimeout creates a new GetWorkflowWorkflowInfosMoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkflowWorkflowInfosMoidParamsWithTimeout(timeout time.Duration) *GetWorkflowWorkflowInfosMoidParams {
	var ()
	return &GetWorkflowWorkflowInfosMoidParams{

		timeout: timeout,
	}
}

// NewGetWorkflowWorkflowInfosMoidParamsWithContext creates a new GetWorkflowWorkflowInfosMoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWorkflowWorkflowInfosMoidParamsWithContext(ctx context.Context) *GetWorkflowWorkflowInfosMoidParams {
	var ()
	return &GetWorkflowWorkflowInfosMoidParams{

		Context: ctx,
	}
}

// NewGetWorkflowWorkflowInfosMoidParamsWithHTTPClient creates a new GetWorkflowWorkflowInfosMoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWorkflowWorkflowInfosMoidParamsWithHTTPClient(client *http.Client) *GetWorkflowWorkflowInfosMoidParams {
	var ()
	return &GetWorkflowWorkflowInfosMoidParams{
		HTTPClient: client,
	}
}

/*GetWorkflowWorkflowInfosMoidParams contains all the parameters to send to the API endpoint
for the get workflow workflow infos moid operation typically these are written to a http.Request
*/
type GetWorkflowWorkflowInfosMoidParams struct {

	/*Moid
	  The moid of the workflowWorkflowInfo instance.

	*/
	Moid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get workflow workflow infos moid params
func (o *GetWorkflowWorkflowInfosMoidParams) WithTimeout(timeout time.Duration) *GetWorkflowWorkflowInfosMoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get workflow workflow infos moid params
func (o *GetWorkflowWorkflowInfosMoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get workflow workflow infos moid params
func (o *GetWorkflowWorkflowInfosMoidParams) WithContext(ctx context.Context) *GetWorkflowWorkflowInfosMoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get workflow workflow infos moid params
func (o *GetWorkflowWorkflowInfosMoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get workflow workflow infos moid params
func (o *GetWorkflowWorkflowInfosMoidParams) WithHTTPClient(client *http.Client) *GetWorkflowWorkflowInfosMoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get workflow workflow infos moid params
func (o *GetWorkflowWorkflowInfosMoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoid adds the moid to the get workflow workflow infos moid params
func (o *GetWorkflowWorkflowInfosMoidParams) WithMoid(moid string) *GetWorkflowWorkflowInfosMoidParams {
	o.SetMoid(moid)
	return o
}

// SetMoid adds the moid to the get workflow workflow infos moid params
func (o *GetWorkflowWorkflowInfosMoidParams) SetMoid(moid string) {
	o.Moid = moid
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowWorkflowInfosMoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param moid
	if err := r.SetPathParam("moid", o.Moid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
