// Code generated by go-swagger; DO NOT EDIT.

package appliance_device_claim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// NewPostApplianceDeviceClaimsParams creates a new PostApplianceDeviceClaimsParams object
// with the default values initialized.
func NewPostApplianceDeviceClaimsParams() *PostApplianceDeviceClaimsParams {
	var ()
	return &PostApplianceDeviceClaimsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostApplianceDeviceClaimsParamsWithTimeout creates a new PostApplianceDeviceClaimsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostApplianceDeviceClaimsParamsWithTimeout(timeout time.Duration) *PostApplianceDeviceClaimsParams {
	var ()
	return &PostApplianceDeviceClaimsParams{

		timeout: timeout,
	}
}

// NewPostApplianceDeviceClaimsParamsWithContext creates a new PostApplianceDeviceClaimsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostApplianceDeviceClaimsParamsWithContext(ctx context.Context) *PostApplianceDeviceClaimsParams {
	var ()
	return &PostApplianceDeviceClaimsParams{

		Context: ctx,
	}
}

// NewPostApplianceDeviceClaimsParamsWithHTTPClient creates a new PostApplianceDeviceClaimsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostApplianceDeviceClaimsParamsWithHTTPClient(client *http.Client) *PostApplianceDeviceClaimsParams {
	var ()
	return &PostApplianceDeviceClaimsParams{
		HTTPClient: client,
	}
}

/*PostApplianceDeviceClaimsParams contains all the parameters to send to the API endpoint
for the post appliance device claims operation typically these are written to a http.Request
*/
type PostApplianceDeviceClaimsParams struct {

	/*Body
	  applianceDeviceClaim to add

	*/
	Body *models.ApplianceDeviceClaim

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post appliance device claims params
func (o *PostApplianceDeviceClaimsParams) WithTimeout(timeout time.Duration) *PostApplianceDeviceClaimsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post appliance device claims params
func (o *PostApplianceDeviceClaimsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post appliance device claims params
func (o *PostApplianceDeviceClaimsParams) WithContext(ctx context.Context) *PostApplianceDeviceClaimsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post appliance device claims params
func (o *PostApplianceDeviceClaimsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post appliance device claims params
func (o *PostApplianceDeviceClaimsParams) WithHTTPClient(client *http.Client) *PostApplianceDeviceClaimsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post appliance device claims params
func (o *PostApplianceDeviceClaimsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post appliance device claims params
func (o *PostApplianceDeviceClaimsParams) WithBody(body *models.ApplianceDeviceClaim) *PostApplianceDeviceClaimsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post appliance device claims params
func (o *PostApplianceDeviceClaimsParams) SetBody(body *models.ApplianceDeviceClaim) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostApplianceDeviceClaimsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
