// Code generated by go-swagger; DO NOT EDIT.

package hyperflex_feature_limit_internal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// GetHyperflexFeatureLimitInternalsReader is a Reader for the GetHyperflexFeatureLimitInternals structure.
type GetHyperflexFeatureLimitInternalsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHyperflexFeatureLimitInternalsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHyperflexFeatureLimitInternalsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetHyperflexFeatureLimitInternalsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetHyperflexFeatureLimitInternalsOK creates a GetHyperflexFeatureLimitInternalsOK with default headers values
func NewGetHyperflexFeatureLimitInternalsOK() *GetHyperflexFeatureLimitInternalsOK {
	return &GetHyperflexFeatureLimitInternalsOK{}
}

/*GetHyperflexFeatureLimitInternalsOK handles this case with default header values.

List of hyperflexFeatureLimitInternals for the given filter criteria
*/
type GetHyperflexFeatureLimitInternalsOK struct {
	Payload *models.HyperflexFeatureLimitInternalList
}

func (o *GetHyperflexFeatureLimitInternalsOK) Error() string {
	return fmt.Sprintf("[GET /hyperflex/FeatureLimitInternals][%d] getHyperflexFeatureLimitInternalsOK  %+v", 200, o.Payload)
}

func (o *GetHyperflexFeatureLimitInternalsOK) GetPayload() *models.HyperflexFeatureLimitInternalList {
	return o.Payload
}

func (o *GetHyperflexFeatureLimitInternalsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HyperflexFeatureLimitInternalList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHyperflexFeatureLimitInternalsDefault creates a GetHyperflexFeatureLimitInternalsDefault with default headers values
func NewGetHyperflexFeatureLimitInternalsDefault(code int) *GetHyperflexFeatureLimitInternalsDefault {
	return &GetHyperflexFeatureLimitInternalsDefault{
		_statusCode: code,
	}
}

/*GetHyperflexFeatureLimitInternalsDefault handles this case with default header values.

Unexpected error
*/
type GetHyperflexFeatureLimitInternalsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get hyperflex feature limit internals default response
func (o *GetHyperflexFeatureLimitInternalsDefault) Code() int {
	return o._statusCode
}

func (o *GetHyperflexFeatureLimitInternalsDefault) Error() string {
	return fmt.Sprintf("[GET /hyperflex/FeatureLimitInternals][%d] GetHyperflexFeatureLimitInternals default  %+v", o._statusCode, o.Payload)
}

func (o *GetHyperflexFeatureLimitInternalsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetHyperflexFeatureLimitInternalsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
