// Code generated by go-swagger; DO NOT EDIT.

package port_sub_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// GetPortSubGroupsReader is a Reader for the GetPortSubGroups structure.
type GetPortSubGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPortSubGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPortSubGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetPortSubGroupsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPortSubGroupsOK creates a GetPortSubGroupsOK with default headers values
func NewGetPortSubGroupsOK() *GetPortSubGroupsOK {
	return &GetPortSubGroupsOK{}
}

/*GetPortSubGroupsOK handles this case with default header values.

List of portSubGroups for the given filter criteria
*/
type GetPortSubGroupsOK struct {
	Payload *models.PortSubGroupList
}

func (o *GetPortSubGroupsOK) Error() string {
	return fmt.Sprintf("[GET /port/SubGroups][%d] getPortSubGroupsOK  %+v", 200, o.Payload)
}

func (o *GetPortSubGroupsOK) GetPayload() *models.PortSubGroupList {
	return o.Payload
}

func (o *GetPortSubGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PortSubGroupList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPortSubGroupsDefault creates a GetPortSubGroupsDefault with default headers values
func NewGetPortSubGroupsDefault(code int) *GetPortSubGroupsDefault {
	return &GetPortSubGroupsDefault{
		_statusCode: code,
	}
}

/*GetPortSubGroupsDefault handles this case with default header values.

Unexpected error
*/
type GetPortSubGroupsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get port sub groups default response
func (o *GetPortSubGroupsDefault) Code() int {
	return o._statusCode
}

func (o *GetPortSubGroupsDefault) Error() string {
	return fmt.Sprintf("[GET /port/SubGroups][%d] GetPortSubGroups default  %+v", o._statusCode, o.Payload)
}

func (o *GetPortSubGroupsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPortSubGroupsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
