// Code generated by go-swagger; DO NOT EDIT.

package adapter_host_fc_interface

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cgascoig/intersight-go/cli/models"
)

// GetAdapterHostFcInterfacesReader is a Reader for the GetAdapterHostFcInterfaces structure.
type GetAdapterHostFcInterfacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAdapterHostFcInterfacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAdapterHostFcInterfacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAdapterHostFcInterfacesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAdapterHostFcInterfacesOK creates a GetAdapterHostFcInterfacesOK with default headers values
func NewGetAdapterHostFcInterfacesOK() *GetAdapterHostFcInterfacesOK {
	return &GetAdapterHostFcInterfacesOK{}
}

/*GetAdapterHostFcInterfacesOK handles this case with default header values.

List of adapterHostFcInterfaces for the given filter criteria
*/
type GetAdapterHostFcInterfacesOK struct {
	Payload *models.AdapterHostFcInterfaceList
}

func (o *GetAdapterHostFcInterfacesOK) Error() string {
	return fmt.Sprintf("[GET /adapter/HostFcInterfaces][%d] getAdapterHostFcInterfacesOK  %+v", 200, o.Payload)
}

func (o *GetAdapterHostFcInterfacesOK) GetPayload() *models.AdapterHostFcInterfaceList {
	return o.Payload
}

func (o *GetAdapterHostFcInterfacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AdapterHostFcInterfaceList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAdapterHostFcInterfacesDefault creates a GetAdapterHostFcInterfacesDefault with default headers values
func NewGetAdapterHostFcInterfacesDefault(code int) *GetAdapterHostFcInterfacesDefault {
	return &GetAdapterHostFcInterfacesDefault{
		_statusCode: code,
	}
}

/*GetAdapterHostFcInterfacesDefault handles this case with default header values.

Unexpected error
*/
type GetAdapterHostFcInterfacesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get adapter host fc interfaces default response
func (o *GetAdapterHostFcInterfacesDefault) Code() int {
	return o._statusCode
}

func (o *GetAdapterHostFcInterfacesDefault) Error() string {
	return fmt.Sprintf("[GET /adapter/HostFcInterfaces][%d] GetAdapterHostFcInterfaces default  %+v", o._statusCode, o.Payload)
}

func (o *GetAdapterHostFcInterfacesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAdapterHostFcInterfacesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
